import os

from setuptools import setup, find_packages

here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, "README.md")) as f:
    README = f.read()
with open(os.path.join(here, "CHANGES.txt")) as f:
    CHANGES = f.read()

requires = [
    "ago",
    "alembic",
    "amqp",
    "appdirs",
    "arrow",
    "async-timeout",
    "attrs",
    "Babel",
    "backports.csv",
    "backports.functools-lru-cache",
    "beautifulsoup4",
    "billiard",
    "binaryornot",
    "black",
    "branca",
    "Brotli",
    "celery",
    "certifi",
    "cffi",
    "Chameleon",
    "chardet",
    "charset-normalizer",
    "cheroot",
    "CherryPy",
    "click",
    "click-didyoumean",
    "click-plugins",
    "click-repl",
    "cookiecutter",
    "coverage",
    "cryptography",
    "cssselect2",
    "decorator",
    "Deprecated",
    "dnspython",
    "docxcompose",
    "docxtpl",
    "et-xmlfile",
    "fanstatic",
    "feedparser",
    "fonttools",
    "FormEncode",
    "future",
    "gevent",
    "greenlet",
    "gunicorn",
    "html5lib",
    "hupper",
    "idna",
    "imgkit",
    "importlib-metadata",
    "importlib-resources",
    "inflect",
    "iniconfig",
    "ipaddress",
    "jaraco.classes",
    "jaraco.collections",
    "jaraco.context",
    "jaraco.functools",
    "jaraco.text",
    "Jinja2",
    "jinja2-time",
    "joblib",
    "kombu",
    "linecache2",
    "lingua",
    "lxml",
    "Mako",
    "MarkupSafe",
    "more-itertools",
    "mypy-extensions",
    "mysql-connector-python",
    "mysqlclient",
    "nltk",
    "nose",
    "numpy",
    "openpyxl",
    "packaging",
    "paginate",
    "pandas",
    "PasteDeploy",
    "pathspec",
    "Pattern",
    "pdfminer.six",
    "Pillow",
    "plaster",
    "plaster-pastedeploy",
    "platformdirs",
    "pluggy",
    "polib",
    "portend",
    "poyo",
    "prompt-toolkit",
    "protobuf",
    "py",
    "pycparser",
    "pycrypto",
    "pycryptodome",
    "pydyf",
    "Pygments",
    "pyparsing",
    "pyphen",
    "pypng",
    "pyramid",
    "pyramid-authstack",
    "pyramid-debugtoolbar",
    "pyramid-fanstatic",
    "pyramid-jinja2",
    "pyramid-mako",
    "pyramid-tm",
    "pyTelegramBotAPI",
    "pytest",
    "pytest-cov",
    "python-dateutil",
    "python-docx",
    "python-editor",
    "python-slugify",
    "pytz",
    "PyUtilib",
    "pyxform",
    "PyYAML",
    "qrcode",
    "qrtools",
    "redis",
    "regex",
    "repoze.lru",
    "requests",
    "rutter",
    "scipy",
    "setproctitle",
    "sgmllib3k",
    "shutilwhich",
    "six",
    "sortedcontainers",
    "soupsieve",
    "SQLAlchemy",
    "SQLAlchemy-Utils",
    "tempora",
    "text-unidecode",
    "timeago",
    "tinycss2",
    "toml",
    "tomli",
    "tqdm",
    "traceback2",
    "transaction",
    "translationstring",
    "typed-ast",
    "typing_extensions",
    "unicodecsv",
    "unittest2",
    "urllib3",
    "validators",
    "venusian",
    "vine",
    "waitress",
    "wcwidth",
    "weasyprint",
    "webencodings",
    "WebHelpers2",
    "WebOb",
    "WebTest",
    "whichcraft",
    "wrapt",
    "xlrd",
    "XlsxWriter",
    "zc.lockfile",
    "zipp",
    "zope.deprecation",
    "zope.event",
    "zope.interface",
    "zope.sqlalchemy",
    "zopfli",
]


tests_require = [
    "WebTest >= 1.3.1",  # py3 compat
    "pytest",
    "pytest-cov",
]

setup(
    name="climmob",
    version="3.9.0",
    description="Climmob",
    long_description=README + "\n\n" + CHANGES,
    classifiers=[
        "Programming Language :: Python",
        "Framework :: Pyramid",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
    ],
    author="Bioverity Internatioanl",
    author_email="c.f.quiros@cgiar.org",
    url="http://climmob.net",
    keywords="web pyramid pylons",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    extras_require={
        "testing": tests_require,
    },
    install_requires=requires,
    entry_points={
        "paste.app_factory": [
            "main = climmob:main",
        ],
        "console_scripts": [
            "configure_mysql = climmob.scripts.configuremysql:main",
            "configure_alembic = climmob.scripts.configurealembic:main",
            "disable_ssl = climmob.scripts.disablessl:main",
            "set_super_password = climmob.scripts.setsuperpassword:main",
            "update_map_points = climmob.scripts.updatemappoints:main",
            "mysqldumps_climmob_dbs = climmob.scripts.mysqldumpclimmobdbs:main",
            "configure_tests = climmob.scripts.configuretests:main",
        ],
    },
)
