"""climmobShare - AssSection - table relationship

Revision ID: 03ec5a4ca463
Revises: ff292d2df278
Create Date: 2021-08-10 10:32:30.819358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03ec5a4ca463"
down_revision = "ff292d2df278"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "asssection", type_="primary")
    op.create_primary_key(
        "pk_asssection", "asssection", ["project_id", "ass_cod", "section_id"]
    )

    op.create_foreign_key(
        op.f("fk_asssection_project_id_assessment"),
        "asssection",
        "assessment",
        ["project_id", "ass_cod"],
        ["project_id", "ass_cod"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "asssection", type_="primary")
    op.create_primary_key(
        "pk_asssection",
        "asssection",
        ["user_name", "project_cod", "ass_cod", "section_id"],
    )

    op.drop_constraint(
        op.f("fk_asssection_project_id_assessment"), "asssection", type_="foreignkey"
    )
    # ### end Alembic commands ###
