"""climmobShare - I18nPrjalia - Remove user_name and project_cod

Revision ID: 0ad2b87a9cc0
Revises: 3b36edef8007
Create Date: 2021-08-18 14:58:09.764735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0ad2b87a9cc0"
down_revision = "3b36edef8007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("i18n_prjalias", "project_cod")
    op.drop_column("i18n_prjalias", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "i18n_prjalias",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "i18n_prjalias",
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
