"""create project anonymization status table

Revision ID: 0e207d9b2dab
Revises: b2b5330dc50d
Create Date: 2026-05-28 09:43:18.168530

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0e207d9b2dab"
down_revision = "b2b5330dc50d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_anonymization_status",
        sa.Column("anonymization_status_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("last_updated_by", sa.Unicode(length=80), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anonymization_status_id"],
            ["anonymization_status.anonymization_status_id"],
            name=op.f(
                "fk_project_anonymization_status_anonymization_status_id_anonymization_status"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by"],
            ["user.user_name"],
            name=op.f("fk_project_anonymization_status_last_updated_by_user"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_project_anonymization_status_project_id_project"),
        ),
        sa.PrimaryKeyConstraint(
            "project_id", name=op.f("pk_project_anonymization_status")
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_anonymization_status")
    # ### end Alembic commands ###
