"""Create tables ProjectMetadataForm

Revision ID: 11734e97442b
Revises: 77090b184211
Create Date: 2024-11-18 14:23:40.260177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "11734e97442b"
down_revision = "77090b184211"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_metadata_form",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("metadata_id", sa.Unicode(length=64), nullable=False),
        sa.Column("pmf_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["metadata_id"],
            ["metadata_form.metadata_id"],
            name=op.f("fk_project_metadata_form_metadata_id_metadata_form"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_project_metadata_form_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "metadata_id", name=op.f("pk_project_metadata_form")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_metadata_form")
    # ### end Alembic commands ###
