"""Update table Question add field question_forms

Revision ID: 136b84259860
Revises: 0176d2461013
Create Date: 2022-04-27 15:31:45.000240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "136b84259860"
down_revision = "0176d2461013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question",
        sa.Column(
            "question_forms", sa.Integer(), server_default=sa.text("'3'"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_forms")
    # ### end Alembic commands ###
