"""create registry_jsonlog

Revision ID: 1748e2fd0987
Revises: 925c0962bca7
Create Date: 2020-02-24 13:04:20.621445

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1748e2fd0987"
down_revision = "925c0962bca7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registry_jsonlog",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("log_id", sa.Unicode(length=64), nullable=False),
        sa.Column("log_dtime", sa.DateTime(), nullable=True),
        sa.Column("json_file", sa.UnicodeText(), nullable=True),
        sa.Column("log_file", sa.UnicodeText(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            ["project.user_name", "project.project_cod"],
            name=op.f("fk_registry_jsonlog_user_name_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "log_id", name=op.f("pk_registry_jsonlog")
        ),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    # op.drop_table('jsonlog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jsonlog",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
        sa.Column("submission_type", mysql.VARCHAR(length=80), nullable=True),
        sa.Column("ass_cod", mysql.VARCHAR(length=80), nullable=False),
        sa.Column("log_id", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("log_dtime", mysql.DATETIME(), nullable=True),
        sa.Column("json_file", mysql.TEXT(), nullable=True),
        sa.Column("log_file", mysql.TEXT(), nullable=True),
        sa.Column(
            "status",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "ass_cod"],
            ["assessment.user_name", "assessment.project_cod", "assessment.ass_cod"],
            name="fk_jsonlog_user_name_assessment",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_name", "project_cod", "ass_cod", "log_id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.drop_table("registry_jsonlog")
    # ### end Alembic commands ###
