"""add field question_quantitative to question

Revision ID: 1b05b458a49d
Revises: d32fefac238b
Create Date: 2021-03-25 10:31:44.818004

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1b05b458a49d"
down_revision = "d32fefac238b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question",
        sa.Column(
            "question_quantitative",
            sa.Integer(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_quantitative")
    # ### end Alembic commands ###
