"""Initial Commit

Revision ID: 1d27a4cea25d
Revises: 
Create Date: 2019-10-02 14:42:55.998138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d27a4cea25d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("cnty_cod", sa.String(length=3), nullable=False),
        sa.Column("cnty_name", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("cnty_cod", name=op.f("pk_country")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "finishedtasks",
        sa.Column("taskid", sa.String(length=80), nullable=False),
        sa.Column("taskerror", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("taskid", name=op.f("pk_finishedtasks")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "i18n",
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("lang_name", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("lang_code", name=op.f("pk_i18n")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "sector",
        sa.Column("sector_cod", sa.Integer(), nullable=False),
        sa.Column("sector_name", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("sector_cod", name=op.f("pk_sector")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "tasks",
        sa.Column("taskid", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("taskid", name=op.f("pk_tasks")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("user_fullname", sa.String(length=120), nullable=True),
        sa.Column("user_password", sa.String(length=80), nullable=True),
        sa.Column("user_organization", sa.String(length=120), nullable=True),
        sa.Column("user_email", sa.String(length=120), nullable=True),
        sa.Column("user_apikey", sa.String(length=45), nullable=True),
        sa.Column("user_about", sa.Text(), nullable=True),
        sa.Column("user_cnty", sa.String(length=3), nullable=False),
        sa.Column("user_sector", sa.Integer(), nullable=False),
        sa.Column(
            "user_active", sa.Integer(), server_default=sa.text(u"'1'"), nullable=True
        ),
        sa.Column("user_joindate", sa.DateTime(), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_cnty"], [u"country.cnty_cod"], name=op.f("fk_user_user_cnty_country")
        ),
        sa.ForeignKeyConstraint(
            ["user_sector"],
            [u"sector.sector_cod"],
            name=op.f("fk_user_user_sector_sector"),
        ),
        sa.PrimaryKeyConstraint("user_name", name=op.f("pk_user")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_user_user_cnty"), "user", ["user_cnty"], unique=False)
    op.create_index(op.f("ix_user_user_sector"), "user", ["user_sector"], unique=False)
    op.create_table(
        "activitylog",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("log_user", sa.String(length=80), nullable=False),
        sa.Column("log_datetime", sa.DateTime(), nullable=True),
        sa.Column("log_type", sa.String(length=3), nullable=True),
        sa.Column("log_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["log_user"], [u"user.user_name"], name=op.f("fk_activitylog_log_user_user")
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_activitylog")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_activitylog_log_user"), "activitylog", ["log_user"], unique=False
    )
    op.create_table(
        "apilog",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("log_datetime", sa.DateTime(), nullable=True),
        sa.Column("log_ip", sa.String(length=45), nullable=True),
        sa.Column("log_user", sa.String(length=80), nullable=False),
        sa.Column("log_uuid", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["log_user"], [u"user.user_name"], name=op.f("fk_apilog_log_user_user")
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_apilog")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_apilog_log_user"), "apilog", ["log_user"], unique=False)
    op.create_table(
        "enumerator",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("enum_id", sa.String(length=80), nullable=False),
        sa.Column("enum_name", sa.String(length=120), nullable=True),
        sa.Column("enum_password", sa.String(length=80), nullable=True),
        sa.Column("enum_active", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name"],
            [u"user.user_name"],
            name=op.f("fk_enumerator_user_name_user"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_name", "enum_id", name=op.f("pk_enumerator")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "project",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("project_name", sa.String(length=120), nullable=True),
        sa.Column("project_abstract", sa.Text(), nullable=True),
        sa.Column("project_tags", sa.Text(), nullable=True),
        sa.Column("project_pi", sa.String(length=120), nullable=True),
        sa.Column("project_piemail", sa.String(length=120), nullable=True),
        sa.Column(
            "project_active",
            sa.Integer(),
            server_default=sa.text(u"'1'"),
            nullable=True,
        ),
        sa.Column(
            "project_public",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "project_dashboard",
            sa.Integer(),
            server_default=sa.text(u"'1'"),
            nullable=True,
        ),
        sa.Column(
            "project_regstatus",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "project_assstatus",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "project_createcomb",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "project_createpkgs",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "project_numobs",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=False,
        ),
        sa.Column("project_numcom", sa.Integer(), nullable=False),
        sa.Column("project_lat", sa.String(length=120), nullable=False),
        sa.Column("project_lon", sa.String(length=120), nullable=False),
        sa.Column("project_creationdate", sa.DateTime(), nullable=False),
        sa.Column(
            "project_localvariety",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name"], [u"user.user_name"], name=op.f("fk_project_user_name_user")
        ),
        sa.PrimaryKeyConstraint("user_name", "project_cod", name=op.f("pk_project")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_project_user_name"), "project", ["user_name"], unique=False
    )
    op.create_table(
        "question",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("question_code", sa.String(length=120), nullable=True),
        sa.Column("question_desc", sa.String(length=120), nullable=True),
        sa.Column("question_notes", sa.Text(), nullable=True),
        sa.Column("question_unit", sa.String(length=120), nullable=True),
        sa.Column("question_dtype", sa.Integer(), nullable=True),
        sa.Column("question_cmp", sa.String(length=120), nullable=True),
        sa.Column(
            "question_reqinreg",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_reqinasses",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_alwaysinreg",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_alwaysinasse",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_optperprj",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column("user_name", sa.String(length=80), nullable=True),
        sa.Column("question_posstm", sa.String(length=120), nullable=True),
        sa.Column("question_negstm", sa.String(length=120), nullable=True),
        sa.Column("question_twoitems", sa.String(length=120), nullable=True),
        sa.Column("question_moreitems", sa.String(length=120), nullable=True),
        sa.Column("question_perfstmt", sa.String(length=120), nullable=True),
        sa.Column("question_requiredvalue", sa.Integer(), nullable=True),
        sa.Column(
            "question_regkey",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_asskey",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_overall",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_overallperf",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_fname",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_district",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_village",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_father",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column(
            "question_visible",
            sa.Integer(),
            server_default=sa.text(u"'0'"),
            nullable=True,
        ),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name"], [u"user.user_name"], name=op.f("fk_question_user_name_user")
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("pk_question")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_question_user_name"), "question", ["user_name"], unique=False
    )
    op.create_table(
        "technology",
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.Column("tech_name", sa.String(length=45), nullable=True),
        sa.Column("user_name", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name"],
            [u"user.user_name"],
            name=op.f("fk_technology_user_name_user"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint("tech_id", name=op.f("pk_technology")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_technology_user_name"), "technology", ["user_name"], unique=False
    )
    op.create_table(
        "assessment",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("ass_cod", sa.String(length=80), nullable=False),
        sa.Column("ass_desc", sa.String(length=120), nullable=True),
        sa.Column("ass_days", sa.Integer(), nullable=True),
        sa.Column(
            "ass_status", sa.Integer(), server_default=sa.text(u"'0'"), nullable=True
        ),
        sa.Column(
            "ass_final", sa.Integer(), server_default=sa.text(u"'0'"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_assessment_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "ass_cod", name=op.f("pk_assessment")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "i18n_project",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("project_name", sa.String(length=120), nullable=True),
        sa.Column("project_abstract", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_project_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_i18n_project_user_name_project"),
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "lang_code", name=op.f("pk_i18n_project")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_project_lang_code"), "i18n_project", ["lang_code"], unique=False
    )
    op.create_table(
        "i18n_question",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("question_desc", sa.String(length=120), nullable=True),
        sa.Column("question_notes", sa.Text(), nullable=True),
        sa.Column("question_unit", sa.String(length=120), nullable=True),
        sa.Column("question_posstm", sa.String(length=120), nullable=True),
        sa.Column("question_negstm", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_question_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            [u"question.question_id"],
            name=op.f("fk_i18n_question_question_id_question"),
        ),
        sa.PrimaryKeyConstraint(
            "question_id", "lang_code", name=op.f("pk_i18n_question")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_question_lang_code"), "i18n_question", ["lang_code"], unique=False
    )
    op.create_table(
        "i18n_technology",
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("tech_name", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_technology_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["tech_id"],
            [u"technology.tech_id"],
            name=op.f("fk_i18n_technology_tech_id_technology"),
        ),
        sa.PrimaryKeyConstraint(
            "tech_id", "lang_code", name=op.f("pk_i18n_technology")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_technology_lang_code"),
        "i18n_technology",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "package",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("package_code", sa.String(length=45), nullable=True),
        sa.Column("package_image", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_package_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "package_id", name=op.f("pk_package")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "prjcnty",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("cnty_cod", sa.String(length=3), nullable=False),
        sa.Column("cnty_contact", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["cnty_cod"],
            [u"country.cnty_cod"],
            name=op.f("fk_prjcnty_cnty_cod_country"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_prjcnty_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "cnty_cod", name=op.f("pk_prjcnty")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_prjcnty_cnty_cod"), "prjcnty", ["cnty_cod"], unique=False)
    op.create_table(
        "prjcombination",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("comb_code", sa.Integer(), nullable=False),
        sa.Column("comb_usable", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_prjcombination_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "comb_code", name=op.f("pk_prjcombination")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "prjenumerator",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("enum_user", sa.String(length=80), nullable=False),
        sa.Column("enum_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["enum_user", "enum_id"],
            [u"enumerator.user_name", u"enumerator.enum_id"],
            name=op.f("fk_prjenumerator_enum_user_enumerator"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_prjenumerator_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "enum_user",
            "enum_id",
            name=op.f("pk_prjenumerator"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "prjlang",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("lang_default", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_prjlang_lang_code_i18n"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_prjlang_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "lang_code", name=op.f("pk_prjlang")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_prjlang_lang_code"), "prjlang", ["lang_code"], unique=False
    )
    op.create_table(
        "prjtech",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tech_id"],
            [u"technology.tech_id"],
            name=op.f("fk_prjtech_tech_id_technology"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_prjtech_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "tech_id", name=op.f("pk_prjtech")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_prjtech_tech_id"), "prjtech", ["tech_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("celery_taskid", sa.String(length=80), nullable=False),
        sa.Column("process_name", sa.String(length=80), nullable=False),
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("product_id", sa.String(length=80), nullable=False),
        sa.Column("output_id", sa.String(length=80), nullable=False),
        sa.Column("output_mimetype", sa.String(length=80), nullable=False),
        sa.Column("datetime_added", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_products_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint("celery_taskid", name=op.f("pk_products")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "qstoption",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("value_code", sa.String(length=80), nullable=False),
        sa.Column("value_desc", sa.String(length=120), nullable=True),
        sa.Column(
            "value_isother", sa.Integer(), server_default=sa.text(u"'0'"), nullable=True
        ),
        sa.Column(
            "value_isna", sa.Integer(), server_default=sa.text(u"'0'"), nullable=True
        ),
        sa.Column(
            "value_order", sa.Integer(), server_default=sa.text(u"'0'"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            [u"question.question_id"],
            name=op.f("fk_qstoption_question_id_question"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint("question_id", "value_code", name=op.f("pk_qstoption")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "regsection",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("section_name", sa.String(length=45), nullable=True),
        sa.Column("section_content", sa.Text(), nullable=True),
        sa.Column("section_order", sa.Integer(), nullable=True),
        sa.Column("section_color", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_regsection_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "section_id", name=op.f("pk_regsection")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "storageerrors",
        sa.Column("fileuid", sa.String(length=80), nullable=False),
        sa.Column("error_datetime", sa.DateTime(), nullable=True),
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("submission_type", sa.String(length=80), nullable=True),
        sa.Column("assessment_id", sa.String(length=80), nullable=True),
        sa.Column("command_executed", sa.Text(), nullable=True),
        sa.Column("error_cod", sa.String(length=80), nullable=True),
        sa.Column("error_des", sa.Text(), nullable=True),
        sa.Column("error_table", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_storageerrors_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint("fileuid", name=op.f("pk_storageerrors")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "techalias",
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("alias_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["tech_id"],
            [u"technology.tech_id"],
            name=op.f("fk_techalias_tech_id_technology"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint("tech_id", "alias_id", name=op.f("pk_techalias")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_techalias_tech_id"), "techalias", ["tech_id"], unique=False
    )
    op.create_table(
        "asssection",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("ass_cod", sa.String(length=80), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("section_name", sa.String(length=120), nullable=True),
        sa.Column("section_content", sa.Text(), nullable=True),
        sa.Column("section_order", sa.Integer(), nullable=True),
        sa.Column("section_color", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "ass_cod"],
            [u"assessment.user_name", u"assessment.project_cod", u"assessment.ass_cod"],
            name=op.f("fk_asssection_user_name_assessment"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "ass_cod",
            "section_id",
            name=op.f("pk_asssection"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "i18n_qstoption",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("value_code", sa.String(length=80), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("value_desc", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_qstoption_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id", "value_code"],
            [u"qstoption.question_id", u"qstoption.value_code"],
            name=op.f("fk_i18n_qstoption_question_id_qstoption"),
        ),
        sa.PrimaryKeyConstraint(
            "question_id", "value_code", "lang_code", name=op.f("pk_i18n_qstoption")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_qstoption_lang_code"),
        "i18n_qstoption",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "i18n_regsection",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("section_name", sa.String(length=120), nullable=True),
        sa.Column("section_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_regsection_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "section_id"],
            [
                u"regsection.user_name",
                u"regsection.project_cod",
                u"regsection.section_id",
            ],
            name=op.f("fk_i18n_regsection_user_name_regsection"),
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "section_id",
            "lang_code",
            name=op.f("pk_i18n_regsection"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_regsection_lang_code"),
        "i18n_regsection",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "i18n_techalias",
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("alias_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_techalias_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["tech_id", "alias_id"],
            [u"techalias.tech_id", u"techalias.alias_id"],
            name=op.f("fk_i18n_techalias_tech_id_techalias"),
        ),
        sa.PrimaryKeyConstraint(
            "tech_id", "alias_id", "lang_code", name=op.f("pk_i18n_techalias")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_techalias_lang_code"),
        "i18n_techalias",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "pkgcomb",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("comb_user", sa.String(length=80), nullable=False),
        sa.Column("comb_project", sa.String(length=80), nullable=False),
        sa.Column("comb_code", sa.Integer(), nullable=False),
        sa.Column("comb_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["comb_user", "comb_project", "comb_code"],
            [
                u"prjcombination.user_name",
                u"prjcombination.project_cod",
                u"prjcombination.comb_code",
            ],
            name=op.f("fk_pkgcomb_comb_user_prjcombination"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "package_id"],
            [u"package.user_name", u"package.project_cod", u"package.package_id"],
            name=op.f("fk_pkgcomb_user_name_package"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "package_id",
            "comb_user",
            "comb_project",
            "comb_code",
            name=op.f("pk_pkgcomb"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_pkgcomb_prjcombination1_idx",
        "pkgcomb",
        ["comb_user", "comb_project", "comb_code"],
        unique=False,
    )
    op.create_table(
        "prjalias",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("alias_name", sa.String(length=120), nullable=True),
        sa.Column("tech_used", sa.Integer(), nullable=True),
        sa.Column("alias_used", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tech_used", "alias_used"],
            [u"techalias.tech_id", u"techalias.alias_id"],
            name=op.f("fk_prjalias_tech_used_techalias"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "tech_id"],
            [u"prjtech.user_name", u"prjtech.project_cod", u"prjtech.tech_id"],
            name=op.f("fk_prjalias_user_name_prjtech"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "tech_id", "alias_id", name=op.f("pk_prjalias")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_prjalias_prjtech1_idx",
        "prjalias",
        ["user_name", "project_cod", "tech_id"],
        unique=False,
    )
    op.create_index(
        "fk_prjalias_techalias1_idx",
        "prjalias",
        ["tech_used", "alias_used"],
        unique=False,
    )
    op.create_table(
        "registry",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("section_user", sa.String(length=80), nullable=True),
        sa.Column("section_project", sa.String(length=80), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("question_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            [u"question.question_id"],
            name=op.f("fk_registry_question_id_question"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_user", "section_project", "section_id"],
            [
                u"regsection.user_name",
                u"regsection.project_cod",
                u"regsection.section_id",
            ],
            name=op.f("fk_registry_section_user_regsection"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod"],
            [u"project.user_name", u"project.project_cod"],
            name=op.f("fk_registry_user_name_project"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name", "project_cod", "question_id", name=op.f("pk_registry")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_registry_regsection1_idx",
        "registry",
        ["section_user", "section_project", "section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registry_question_id"), "registry", ["question_id"], unique=False
    )
    op.create_table(
        "assdetail",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("ass_cod", sa.String(length=80), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("section_user", sa.String(length=80), nullable=False),
        sa.Column("section_project", sa.String(length=80), nullable=False),
        sa.Column("section_assessment", sa.String(length=80), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("question_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            [u"question.question_id"],
            name=op.f("fk_assdetail_question_id_question"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_user", "section_project", "section_assessment", "section_id"],
            [
                u"asssection.user_name",
                u"asssection.project_cod",
                u"asssection.ass_cod",
                u"asssection.section_id",
            ],
            name=op.f("fk_assdetail_section_user_asssection"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "ass_cod"],
            [u"assessment.user_name", u"assessment.project_cod", u"assessment.ass_cod"],
            name=op.f("fk_assdetail_user_name_assessment"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "ass_cod",
            "question_id",
            name=op.f("pk_assdetail"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_assessment_asssection1_idx",
        "assdetail",
        ["section_user", "section_project", "section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assdetail_question_id"), "assdetail", ["question_id"], unique=False
    )
    op.create_table(
        "i18n_asssection",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("ass_cod", sa.String(length=80), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("section_name", sa.String(length=120), nullable=True),
        sa.Column("section_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_asssection_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "ass_cod", "section_id"],
            [
                u"asssection.user_name",
                u"asssection.project_cod",
                u"asssection.ass_cod",
                u"asssection.section_id",
            ],
            name=op.f("fk_i18n_asssection_user_name_asssection"),
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "ass_cod",
            "section_id",
            "lang_code",
            name=op.f("pk_i18n_asssection"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_asssection_lang_code"),
        "i18n_asssection",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "i18n_prjalias",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("alias_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            [u"i18n.lang_code"],
            name=op.f("fk_i18n_prjalias_lang_code_i18n"),
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "tech_id", "alias_id"],
            [
                u"prjalias.user_name",
                u"prjalias.project_cod",
                u"prjalias.tech_id",
                u"prjalias.alias_id",
            ],
            name=op.f("fk_i18n_prjalias_user_name_prjalias"),
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "tech_id",
            "alias_id",
            "lang_code",
            name=op.f("pk_i18n_prjalias"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_prjalias_lang_code"), "i18n_prjalias", ["lang_code"], unique=False
    )
    op.create_table(
        "prjcombdet",
        sa.Column("prjcomb_user", sa.String(length=80), nullable=False),
        sa.Column("prjcomb_project", sa.String(length=80), nullable=False),
        sa.Column("comb_code", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("tech_id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("alias_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prjcomb_user", "prjcomb_project", "comb_code"],
            [
                u"prjcombination.user_name",
                u"prjcombination.project_cod",
                u"prjcombination.comb_code",
            ],
            name=op.f("fk_prjcombdet_prjcomb_user_prjcombination"),
            ondelete=u"CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "tech_id", "alias_id"],
            [
                u"prjalias.user_name",
                u"prjalias.project_cod",
                u"prjalias.tech_id",
                u"prjalias.alias_id",
            ],
            name=op.f("fk_prjcombdet_user_name_prjalias"),
            ondelete=u"CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "prjcomb_user",
            "prjcomb_project",
            "comb_code",
            "user_name",
            "project_cod",
            "tech_id",
            "alias_id",
            name=op.f("pk_prjcombdet"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_prjcombdet_prjalias1_idx",
        "prjcombdet",
        ["user_name", "project_cod", "tech_id", "alias_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("fk_prjcombdet_prjalias1_idx", table_name="prjcombdet")
    op.drop_table("prjcombdet")
    op.drop_index(op.f("ix_i18n_prjalias_lang_code"), table_name="i18n_prjalias")
    op.drop_table("i18n_prjalias")
    op.drop_index(op.f("ix_i18n_asssection_lang_code"), table_name="i18n_asssection")
    op.drop_table("i18n_asssection")
    op.drop_index(op.f("ix_assdetail_question_id"), table_name="assdetail")
    op.drop_index("fk_assessment_asssection1_idx", table_name="assdetail")
    op.drop_table("assdetail")
    op.drop_index(op.f("ix_registry_question_id"), table_name="registry")
    op.drop_index("fk_registry_regsection1_idx", table_name="registry")
    op.drop_table("registry")
    op.drop_index("fk_prjalias_techalias1_idx", table_name="prjalias")
    op.drop_index("fk_prjalias_prjtech1_idx", table_name="prjalias")
    op.drop_table("prjalias")
    op.drop_index("fk_pkgcomb_prjcombination1_idx", table_name="pkgcomb")
    op.drop_table("pkgcomb")
    op.drop_index(op.f("ix_i18n_techalias_lang_code"), table_name="i18n_techalias")
    op.drop_table("i18n_techalias")
    op.drop_index(op.f("ix_i18n_regsection_lang_code"), table_name="i18n_regsection")
    op.drop_table("i18n_regsection")
    op.drop_index(op.f("ix_i18n_qstoption_lang_code"), table_name="i18n_qstoption")
    op.drop_table("i18n_qstoption")
    op.drop_table("asssection")
    op.drop_index(op.f("ix_techalias_tech_id"), table_name="techalias")
    op.drop_table("techalias")
    op.drop_table("storageerrors")
    op.drop_table("regsection")
    op.drop_table("qstoption")
    op.drop_table("products")
    op.drop_index(op.f("ix_prjtech_tech_id"), table_name="prjtech")
    op.drop_table("prjtech")
    op.drop_index(op.f("ix_prjlang_lang_code"), table_name="prjlang")
    op.drop_table("prjlang")
    op.drop_table("prjenumerator")
    op.drop_table("prjcombination")
    op.drop_index(op.f("ix_prjcnty_cnty_cod"), table_name="prjcnty")
    op.drop_table("prjcnty")
    op.drop_table("package")
    op.drop_index(op.f("ix_i18n_technology_lang_code"), table_name="i18n_technology")
    op.drop_table("i18n_technology")
    op.drop_index(op.f("ix_i18n_question_lang_code"), table_name="i18n_question")
    op.drop_table("i18n_question")
    op.drop_index(op.f("ix_i18n_project_lang_code"), table_name="i18n_project")
    op.drop_table("i18n_project")
    op.drop_table("assessment")
    op.drop_index(op.f("ix_technology_user_name"), table_name="technology")
    op.drop_table("technology")
    op.drop_index(op.f("ix_question_user_name"), table_name="question")
    op.drop_table("question")
    op.drop_index(op.f("ix_project_user_name"), table_name="project")
    op.drop_table("project")
    op.drop_table("enumerator")
    op.drop_index(op.f("ix_apilog_log_user"), table_name="apilog")
    op.drop_table("apilog")
    op.drop_index(op.f("ix_activitylog_log_user"), table_name="activitylog")
    op.drop_table("activitylog")
    op.drop_index(op.f("ix_user_user_sector"), table_name="user")
    op.drop_index(op.f("ix_user_user_cnty"), table_name="user")
    op.drop_table("user")
    op.drop_table("tasks")
    op.drop_table("sector")
    op.drop_table("i18n")
    op.drop_table("finishedtasks")
    op.drop_table("country")
    # ### end Alembic commands ###
