"""climmobShare - AssessmentJsonLog - add project_id

Revision ID: 1e2e5925c3c9
Revises: 513d1f08ddc4
Create Date: 2021-08-03 13:24:37.276454

"""
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e2e5925c3c9"
down_revision = "513d1f08ddc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assesment_jsonlog",
        sa.Column("project_id", sa.Unicode(length=64), nullable=True),
    )

    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project")
        for project in projects:
            session.execute(
                "UPDATE assesment_jsonlog SET project_id = '"
                + project.project_id
                + "' WHERE (user_name = '"
                + project.user_name
                + "') and (project_cod = '"
                + project.project_cod
                + "');"
            )
    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assesment_jsonlog", "project_id")
    # ### end Alembic commands ###
