"""Add field question_lang to Question

Revision ID: 1f4057c63fb9
Revises: e3dd7e27aa2e
Create Date: 2023-04-18 09:32:57.974763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1f4057c63fb9"
down_revision = "e3dd7e27aa2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question", sa.Column("question_lang", sa.Unicode(length=5), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_question_question_lang_i18n"),
        "question",
        "i18n",
        ["question_lang"],
        ["lang_code"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_question_question_lang_i18n"), "question", type_="foreignkey"
    )
    op.drop_column("question", "question_lang")
    # ### end Alembic commands ###
