"""Create table LocationUnitOfAnalysisObjectives

Revision ID: 211488d0c5d9
Revises: d30d9bf7cd9e
Create Date: 2024-12-06 14:26:07.629658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "211488d0c5d9"
down_revision = "d30d9bf7cd9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_unit_of_analysis_objectives",
        sa.Column("pluoaobj_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pluoa_id", sa.Integer(), nullable=True),
        sa.Column("pobjective_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pluoa_id"],
            ["location_unit_of_analysis.pluoa_id"],
            name=op.f(
                "fk_location_unit_of_analysis_objectives_pluoa_id_location_unit_of_analysis"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pobjective_id"],
            ["project_objective.pobjective_id"],
            name=op.f(
                "fk_location_unit_of_analysis_objectives_pobjective_id_project_objective"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "pluoaobj_id", name=op.f("pk_location_unit_of_analysis_objectives")
        ),
        sa.UniqueConstraint(
            "pluoa_id", "pobjective_id", name="uq_pluoa_id_pobjective_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location_unit_of_analysis_objectives")
    # ### end Alembic commands ###
