"""Create table LocationUnitOfAnalysisObjectives

Revision ID: 211488d0c5d9
Revises: d30d9bf7cd9e
Create Date: 2024-12-06 14:26:07.629658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "211488d0c5d9"
down_revision = "d30d9bf7cd9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_unit_of_analysis_objectives",
        sa.Column("pluoaobj_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pluoa_id", sa.Integer(), nullable=True),
        sa.Column("pobjective_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pluoa_id"],
            ["location_unit_of_analysis.pluoa_id"],
            name=op.f(
                "fk_location_unit_of_analysis_objectives_pluoa_id_location_unit_of_analysis"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pobjective_id"],
            ["project_objective.pobjective_id"],
            name=op.f(
                "fk_location_unit_of_analysis_objectives_pobjective_id_project_objective"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "pluoaobj_id", name=op.f("pk_location_unit_of_analysis_objectives")
        ),
        sa.UniqueConstraint(
            "pluoa_id", "pobjective_id", name="uq_pluoa_id_pobjective_id"
        ),
    )

    project_location_unit_of_analysis_objectives_values = [
        {"pluoaobj_id": 1, "pluoa_id": 1, "pobjective_id": 6},
        {"pluoaobj_id": 2, "pluoa_id": 1, "pobjective_id": 7},
        {"pluoaobj_id": 3, "pluoa_id": 1, "pobjective_id": 9},
        {"pluoaobj_id": 4, "pluoa_id": 1, "pobjective_id": 10},
        {"pluoaobj_id": 5, "pluoa_id": 1, "pobjective_id": 11},
        {"pluoaobj_id": 6, "pluoa_id": 1, "pobjective_id": 12},
        {"pluoaobj_id": 7, "pluoa_id": 2, "pobjective_id": 1},
        {"pluoaobj_id": 8, "pluoa_id": 2, "pobjective_id": 3},
        {"pluoaobj_id": 9, "pluoa_id": 2, "pobjective_id": 7},
        {"pluoaobj_id": 10, "pluoa_id": 2, "pobjective_id": 8},
        {"pluoaobj_id": 11, "pluoa_id": 3, "pobjective_id": 1},
        {"pluoaobj_id": 12, "pluoa_id": 3, "pobjective_id": 3},
        {"pluoaobj_id": 13, "pluoa_id": 3, "pobjective_id": 7},
        {"pluoaobj_id": 14, "pluoa_id": 3, "pobjective_id": 8},
        {"pluoaobj_id": 15, "pluoa_id": 4, "pobjective_id": 4},
        {"pluoaobj_id": 16, "pluoa_id": 4, "pobjective_id": 5},
        {"pluoaobj_id": 17, "pluoa_id": 4, "pobjective_id": 7},
        {"pluoaobj_id": 18, "pluoa_id": 4, "pobjective_id": 9},
        {"pluoaobj_id": 19, "pluoa_id": 5, "pobjective_id": 6},
        {"pluoaobj_id": 20, "pluoa_id": 5, "pobjective_id": 7},
        {"pluoaobj_id": 21, "pluoa_id": 5, "pobjective_id": 9},
        {"pluoaobj_id": 22, "pluoa_id": 5, "pobjective_id": 10},
        {"pluoaobj_id": 23, "pluoa_id": 5, "pobjective_id": 11},
        {"pluoaobj_id": 24, "pluoa_id": 5, "pobjective_id": 12},
        {"pluoaobj_id": 25, "pluoa_id": 6, "pobjective_id": 2},
        {"pluoaobj_id": 26, "pluoa_id": 6, "pobjective_id": 7},
        {"pluoaobj_id": 27, "pluoa_id": 7, "pobjective_id": 6},
        {"pluoaobj_id": 28, "pluoa_id": 7, "pobjective_id": 7},
        {"pluoaobj_id": 29, "pluoa_id": 7, "pobjective_id": 9},
        {"pluoaobj_id": 30, "pluoa_id": 7, "pobjective_id": 10},
        {"pluoaobj_id": 31, "pluoa_id": 7, "pobjective_id": 11},
        {"pluoaobj_id": 32, "pluoa_id": 7, "pobjective_id": 12},
        {"pluoaobj_id": 33, "pluoa_id": 8, "pobjective_id": 2},
        {"pluoaobj_id": 34, "pluoa_id": 8, "pobjective_id": 7},
    ]

    project_location_unit_of_analysis_objectives = table(
        "location_unit_of_analysis_objectives",
        column("pluoaobj_id", Integer),
        column("pluoa_id", Integer),
        column("pobjective_id", Integer),
    )
    op.bulk_insert(
        project_location_unit_of_analysis_objectives,
        project_location_unit_of_analysis_objectives_values,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location_unit_of_analysis_objectives")
    # ### end Alembic commands ###
