"""climmobShare - Package - table relationship

Revision ID: 2368b6225583
Revises: 1827cbfc4260
Create Date: 2021-08-10 11:43:33.792636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2368b6225583"
down_revision = "1827cbfc4260"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "package", type_="primary")
    op.create_primary_key("pk_package", "package", ["project_id", "package_id"])

    op.create_foreign_key(
        op.f("fk_package_project_id_project"),
        "package",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "package", type_="primary")
    op.create_primary_key(
        "pk_package", "package", ["user_name", "project_cod", "package_id"]
    )

    op.drop_constraint(
        op.f("fk_package_project_id_project"), "package", type_="foreignkey"
    )
    # ### end Alembic commands ###
