"""climmobShare - Pkgcomb - Remove user_name and project_cod

Revision ID: 2410620cc477
Revises: 37e2b14fc391
Create Date: 2021-08-26 11:39:21.798991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2410620cc477"
down_revision = "37e2b14fc391"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pkgcomb", "user_name")
    op.drop_column("pkgcomb", "comb_project")
    op.drop_column("pkgcomb", "comb_user")
    op.drop_column("pkgcomb", "project_cod")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pkgcomb", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "pkgcomb", sa.Column("comb_user", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "pkgcomb", sa.Column("comb_project", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "pkgcomb", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    # ### end Alembic commands ###
