"""climmobShare - Prjcombination - table relationship

Revision ID: 2619a91dc4a0
Revises: 2368b6225583
Create Date: 2021-08-10 13:40:00.169569

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2619a91dc4a0"
down_revision = "2368b6225583"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjcombination", type_="primary")
    op.create_primary_key(
        "pk_prjcombination", "prjcombination", ["project_id", "comb_code"]
    )

    op.create_foreign_key(
        op.f("fk_prjcombination_project_id_project"),
        "prjcombination",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjcombination", type_="primary")
    op.create_primary_key(
        "pk_prjcombination", "prjcombination", ["user_name", "project_cod", "comb_code"]
    )

    op.drop_constraint(
        op.f("fk_prjcombination_project_id_project"),
        "prjcombination",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
