"""Create table i18n_country

Revision ID: 2b7f3eef2437
Revises: 3ad67ced2915
Create Date: 2024-07-16 10:27:17.189943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2b7f3eef2437"
down_revision = "3ad67ced2915"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "i18n_country",
        sa.Column("cnty_cod", sa.Unicode(length=3), nullable=False),
        sa.Column("lang_code", sa.Unicode(length=5), nullable=False),
        sa.Column("cnty_name", sa.Unicode(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["cnty_cod"],
            ["country.cnty_cod"],
            name=op.f("fk_i18n_country_cnty_cod_country"),
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["i18n.lang_code"],
            name=op.f("fk_i18n_country_lang_code_i18n"),
        ),
        sa.PrimaryKeyConstraint("cnty_cod", "lang_code", name=op.f("pk_i18n_country")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.add_column(
        "country",
        sa.Column(
            "cnty_lang",
            sa.Unicode(length=5),
            server_default=sa.text("'en'"),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_country_cnty_lang_i18n"),
        "country",
        "i18n",
        ["cnty_lang"],
        ["lang_code"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_country_cnty_lang_i18n"), "country", type_="foreignkey")
    op.drop_column("country", "cnty_lang")
    op.drop_table("i18n_country")
    # ### end Alembic commands ###
