"""Adding the metadata_for_technology_options field to the MetadataForm table

Revision ID: 2bca2728583a
Revises: 5585a156b4b8
Create Date: 2025-04-08 09:35:48.106928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2bca2728583a"
down_revision = "5585a156b4b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metadata_form",
        sa.Column(
            "metadata_for_technology_options",
            sa.Integer(),
            server_default=sa.text("'0'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metadata_form", "metadata_for_technology_options")
    # ### end Alembic commands ###
