"""climmobShare - i18nRegsection - add project_id

Revision ID: 2c52bd24de78
Revises: 6d0e0e657eff
Create Date: 2021-08-03 11:50:46.027042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from climmob.models.climmobv4 import I18nRegsection, Project

# revision identifiers, used by Alembic.
revision = "2c52bd24de78"
down_revision = "6d0e0e657eff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "i18n_regsection", sa.Column("project_id", sa.Unicode(length=64), nullable=True)
    )

    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project")
        for project in projects:
            session.execute(
                "UPDATE i18n_regsection SET project_id = '"
                + project.project_id
                + "' WHERE (user_name = '"
                + project.user_name
                + "') and (project_cod = '"
                + project.project_cod
                + "');"
            )
    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("i18n_regsection", "project_id")
    # ### end Alembic commands ###
