"""create anonymization-param table

Revision ID: 2e83eeec0f3a
Revises: d7b924f3f3d5
Create Date: 2026-05-27 09:24:15.160294

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2e83eeec0f3a"
down_revision = "d7b924f3f3d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymization_parameter",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=64), nullable=False),
        sa.Column("value", sa.Unicode(length=64), nullable=False),
        sa.PrimaryKeyConstraint(
            "question_id", "name", name=op.f("pk_anonymization_parameter")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anonymization_parameter")
    # ### end Alembic commands ###
