"""Create table LocationUnitOfAnalysis

Revision ID: 2fbe0f0d4e88
Revises: 11734e97442b
Create Date: 2024-11-20 09:43:14.295223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "2fbe0f0d4e88"
down_revision = "11734e97442b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_unit_of_analysis",
        sa.Column("pluoa_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plocation_id", sa.Integer(), nullable=True),
        sa.Column("puoa_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plocation_id"],
            ["project_location.plocation_id"],
            name=op.f("fk_location_unit_of_analysis_plocation_id_project_location"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["puoa_id"],
            ["project_unit_of_analysis.puoa_id"],
            name=op.f("fk_location_unit_of_analysis_puoa_id_project_unit_of_analysis"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pluoa_id", name=op.f("pk_location_unit_of_analysis")),
        sa.UniqueConstraint("plocation_id", "puoa_id", name="uq_plocation_id_puoa_id"),
    )

    project_location_unit_of_analysis_values = [
        {
            "pluoa_id": 1,
            "plocation_id": 1,
            "puoa_id": 4,
        },
        {
            "pluoa_id": 2,
            "plocation_id": 1,
            "puoa_id": 1,
        },
        {
            "pluoa_id": 3,
            "plocation_id": 1,
            "puoa_id": 2,
        },
        {
            "pluoa_id": 4,
            "plocation_id": 1,
            "puoa_id": 5,
        },
        {
            "pluoa_id": 5,
            "plocation_id": 2,
            "puoa_id": 3,
        },
        {
            "pluoa_id": 6,
            "plocation_id": 2,
            "puoa_id": 6,
        },
        {
            "pluoa_id": 7,
            "plocation_id": 3,
            "puoa_id": 3,
        },
        {
            "pluoa_id": 8,
            "plocation_id": 3,
            "puoa_id": 6,
        },
    ]

    project_location_unit_of_analysis = table(
        "location_unit_of_analysis",
        column("pluoa_id", Integer),
        column("plocation_id", Integer),
        column("puoa_id", Integer),
    )
    op.bulk_insert(
        project_location_unit_of_analysis, project_location_unit_of_analysis_values
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location_unit_of_analysis")
    # ### end Alembic commands ###
