"""Create table LocationUnitOfAnalysis

Revision ID: 2fbe0f0d4e88
Revises: 11734e97442b
Create Date: 2024-11-20 09:43:14.295223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2fbe0f0d4e88"
down_revision = "11734e97442b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_unit_of_analysis",
        sa.Column("pluoa_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plocation_id", sa.Integer(), nullable=False),
        sa.Column("puoa_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plocation_id"],
            ["project_location.plocation_id"],
            name=op.f("fk_location_unit_of_analysis_plocation_id_project_location"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["puoa_id"],
            ["project_unit_of_analysis.puoa_id"],
            name=op.f("fk_location_unit_of_analysis_puoa_id_project_unit_of_analysis"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "plocation_id", "puoa_id", name=op.f("pk_location_unit_of_analysis")
        ),
        sa.UniqueConstraint(
            "pluoa_id", name=op.f("uq_location_unit_of_analysis_pluoa_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location_unit_of_analysis")
    # ### end Alembic commands ###
