"""Add field registration_and_analysis to Table LocationUnitOfAnalysis

Revision ID: 309b5898cb78
Revises: 9b21c62e9f88
Create Date: 2024-12-11 15:12:11.405594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "309b5898cb78"
down_revision = "9b21c62e9f88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location_unit_of_analysis",
        sa.Column(
            "registration_and_analysis",
            sa.Integer(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )

    session = Session(bind=op.get_bind())
    try:
        session.execute(
            "UPDATE location_unit_of_analysis SET registration_and_analysis = '1' WHERE (pluoa_id = '5');"
        )
        session.execute(
            "UPDATE location_unit_of_analysis SET registration_and_analysis = '1' WHERE (pluoa_id = '6');"
        )
    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location_unit_of_analysis", "registration_and_analysis")
    # ### end Alembic commands ###
