"""climmobShare - Package - Remove user_name and project_cod

Revision ID: 37e2b14fc391
Revises: 641494781663
Create Date: 2021-08-26 11:36:41.352933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "37e2b14fc391"
down_revision = "641494781663"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("package", "project_cod")
    op.drop_column("package", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "package", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "package", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    # ### end Alembic commands ###
