"""climmobShare - PrjTech - Remove user_name and project_cod

Revision ID: 3946605a6354
Revises: 6efa7642db00
Create Date: 2021-08-18 13:41:01.775741

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3946605a6354"
down_revision = "6efa7642db00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prjtech", "user_name")
    op.drop_column("prjtech", "project_cod")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prjtech", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "prjtech", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    # ### end Alembic commands ###
