"""climmobShare - I18nProject - table relationship

Revision ID: 3ab4cb6630be
Revises: bcbf7a156daf
Create Date: 2021-08-10 14:38:13.981675

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ab4cb6630be"
down_revision = "bcbf7a156daf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "i18n_project", type_="primary")
    op.create_primary_key(
        "pk_i18n_project", "i18n_project", ["project_id", "lang_code"]
    )

    op.create_foreign_key(
        op.f("fk_i18n_project_project_id_project"),
        "i18n_project",
        "project",
        ["project_id"],
        ["project_id"],
    )
    op.create_foreign_key(
        op.f("fk_i18n_project_lang_code_i18n"),
        "i18n_project",
        "i18n",
        ["lang_code"],
        ["lang_code"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "i18n_project", type_="primary")
    op.create_primary_key(
        "pk_i18n_project", "i18n_project", ["user_name", "project_cod", "lang_code"]
    )

    op.drop_constraint(
        op.f("fk_i18n_project_lang_code_i18n"), "i18n_project", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_i18n_project_project_id_project"), "i18n_project", type_="foreignkey"
    )
    # ### end Alembic commands ###
