"""climmobShare - I18nAsssection - Remove user_name and project_cod

Revision ID: 3b36edef8007
Revises: cc4b990f6e67
Create Date: 2021-08-18 14:52:55.386454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3b36edef8007"
down_revision = "cc4b990f6e67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("i18n_asssection", "project_cod")
    op.drop_column("i18n_asssection", "user_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "i18n_asssection",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "i18n_asssection",
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
