"""no delete cascade tables _jsonlog

Revision ID: 3f2fa668dbac
Revises: 5dade0633cee
Create Date: 2020-02-25 13:10:20.636855

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f2fa668dbac"
down_revision = "5dade0633cee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_assesment_jsonlog_enum_user_enumerator",
        "assesment_jsonlog",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_assesment_jsonlog_user_name_assessment",
        "assesment_jsonlog",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_assesment_jsonlog_enum_user_enumerator"),
        "assesment_jsonlog",
        "enumerator",
        ["enum_user", "enum_id"],
        ["user_name", "enum_id"],
    )
    op.create_foreign_key(
        op.f("fk_assesment_jsonlog_user_name_assessment"),
        "assesment_jsonlog",
        "assessment",
        ["user_name", "project_cod", "ass_cod"],
        ["user_name", "project_cod", "ass_cod"],
    )
    op.drop_constraint(
        "fk_registry_jsonlog_user_name_project", "registry_jsonlog", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_registry_jsonlog_enum_user_enumerator",
        "registry_jsonlog",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_registry_jsonlog_user_name_project"),
        "registry_jsonlog",
        "project",
        ["user_name", "project_cod"],
        ["user_name", "project_cod"],
    )
    op.create_foreign_key(
        op.f("fk_registry_jsonlog_enum_user_enumerator"),
        "registry_jsonlog",
        "enumerator",
        ["enum_user", "enum_id"],
        ["user_name", "enum_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_registry_jsonlog_enum_user_enumerator"),
        "registry_jsonlog",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_registry_jsonlog_user_name_project"),
        "registry_jsonlog",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_registry_jsonlog_enum_user_enumerator",
        "registry_jsonlog",
        "enumerator",
        ["enum_user", "enum_id"],
        ["user_name", "enum_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_registry_jsonlog_user_name_project",
        "registry_jsonlog",
        "project",
        ["user_name", "project_cod"],
        ["user_name", "project_cod"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_assesment_jsonlog_user_name_assessment"),
        "assesment_jsonlog",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_assesment_jsonlog_enum_user_enumerator"),
        "assesment_jsonlog",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_assesment_jsonlog_user_name_assessment",
        "assesment_jsonlog",
        "assessment",
        ["user_name", "project_cod", "ass_cod"],
        ["user_name", "project_cod", "ass_cod"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_assesment_jsonlog_enum_user_enumerator",
        "assesment_jsonlog",
        "enumerator",
        ["enum_user", "enum_id"],
        ["user_name", "enum_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
