"""create tables for i18ncrops

Revision ID: 4292187fbaf1
Revises: a65f249977b8
Create Date: 2020-11-10 12:00:06.817177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4292187fbaf1"
down_revision = "a65f249977b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_alias",
        sa.Column("crop_cod", sa.String(length=12), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("alias_cod", sa.String(length=12), nullable=False),
        sa.Column("alias_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["crop_cod"],
            ["crops.crop_cod"],
            name=op.f("fk_crop_alias_crop_cod_crops"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"], ["i18n.lang_code"], name=op.f("fk_crop_alias_lang_code_i18n")
        ),
        sa.PrimaryKeyConstraint(
            "crop_cod", "lang_code", "alias_cod", name=op.f("pk_crop_alias")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_crop_alias_crop_cod"), "crop_alias", ["crop_cod"], unique=False
    )
    op.create_index(
        op.f("ix_crop_alias_lang_code"), "crop_alias", ["lang_code"], unique=False
    )
    op.create_table(
        "i18n_crop_categories",
        sa.Column("category_cod", sa.String(length=12), nullable=False),
        sa.Column("lang_code", sa.String(length=5), nullable=False),
        sa.Column("category_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_cod"],
            ["crop_categories.category_cod"],
            name=op.f("fk_i18n_crop_categories_category_cod_crop_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["i18n.lang_code"],
            name=op.f("fk_i18n_crop_categories_lang_code_i18n"),
        ),
        sa.PrimaryKeyConstraint(
            "category_cod", "lang_code", name=op.f("pk_i18n_crop_categories")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_i18n_crop_categories_category_cod"),
        "i18n_crop_categories",
        ["category_cod"],
        unique=False,
    )
    op.create_index(
        op.f("ix_i18n_crop_categories_lang_code"),
        "i18n_crop_categories",
        ["lang_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_i18n_crop_categories_lang_code"), table_name="i18n_crop_categories"
    )
    op.drop_index(
        op.f("ix_i18n_crop_categories_category_cod"), table_name="i18n_crop_categories"
    )
    op.drop_table("i18n_crop_categories")
    op.drop_index(op.f("ix_crop_alias_lang_code"), table_name="crop_alias")
    op.drop_index(op.f("ix_crop_alias_crop_cod"), table_name="crop_alias")
    op.drop_table("crop_alias")
    # ### end Alembic commands ###
