"""climmobShare - Project - add project_id

Revision ID: 4879489bef8d
Revises: 8f9c1f3f2153
Create Date: 2021-08-03 10:43:53.827870

"""
from alembic import op
import sqlalchemy as sa
from climmob.models.climmobv4 import Project
from climmob.models import mapToSchema
import uuid
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "4879489bef8d"
down_revision = "8f9c1f3f2153"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("project_id", sa.Unicode(length=64), nullable=True)
    )

    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project")
        for project in projects:
            session.execute(
                "UPDATE project SET project_id = '"
                + uuid.uuid4().hex[-12:]
                + "' WHERE (user_name = '"
                + project.user_name
                + "') and (project_cod = '"
                + project.project_cod
                + "');"
            )

    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_id")
    # ### end Alembic commands ###
