"""Add continent at country level

Revision ID: 4902d1329fa9
Revises: c61ba397e432
Create Date: 2025-04-30 08:30:44.917111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4902d1329fa9"
down_revision = "c61ba397e432"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_project_project_continent_continent"), "project", type_="foreignkey"
    )
    op.drop_column("project", "project_continent")

    op.add_column("country", sa.Column("cnty_continent", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_country_cnty_continent_continent"),
        "country",
        "continent",
        ["cnty_continent"],
        ["continent_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_country_cnty_continent_continent"), "country", type_="foreignkey"
    )
    op.drop_column("country", "cnty_continent")

    op.add_column(
        "project", sa.Column("project_continent", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_project_project_continent_continent"),
        "project",
        "continent",
        ["project_continent"],
        ["continent_id"],
    )
    # ### end Alembic commands ###
