"""Add continent at country level

Revision ID: 4902d1329fa9
Revises: c61ba397e432
Create Date: 2025-04-30 08:30:44.917111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "4902d1329fa9"
down_revision = "c61ba397e432"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_project_project_continent_continent"), "project", type_="foreignkey"
    )
    op.drop_column("project", "project_continent")

    op.add_column("country", sa.Column("cnty_continent", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_country_cnty_continent_continent"),
        "country",
        "continent",
        ["cnty_continent"],
        ["continent_id"],
    )

    session = Session(bind=op.get_bind())
    try:
        session.execute(
            "update country set cnty_continent = 1 where (cnty_cod in('AG','AI','AR','AW','BB','BL','BM','BO','BQ',"
            "'BR','BS','BZ','CA','CL','CO','CR','CU','CW','DM','DO','EC','FK','GD','GF','GL','GP','GT','GY','HN',"
            "'HT','JM','KN','KY','LC','MF','MQ','MS','MX','NI','PA','PE','PM','PR','PY','SR','SV','SX','TC','TT',"
            "'US','UY','VC','VE','VG','VI'));"
        )
        session.execute(
            "update country set cnty_continent = 2 where (cnty_cod in('AQ','BV','GS','HM','TF'));"
        )

        session.execute(
            "update country set cnty_continent = 3 where (cnty_cod in('AD','AL','AT','AX','BA','BE','BG',"
            "'BY','CH','CY','CZ','DE','DK','EE','ES','FI','FO','FR','GB','GG','GI','GR','HR','HU','IE',"
            "'IM','IS','IT','JE','LI','LT','LU','LV','MC','MD','ME','MK','MT','NL','NO','PL','PT','RO',"
            "'RS','RU','SE','SI','SJ','SK','SM','UA','VA'));"
        )

        session.execute(
            "update country set cnty_continent = 4 where (cnty_cod in('AE','AF','AM','AZ','BD','BH','BN',"
            "'BT','CC','CN','CX','GE','HK','ID','IL','IN','IO','IQ','IR','JO','JP','KG','KH','KP','KR',"
            "'KW','KZ','LA','LB','LK','MM','MN','MO','MV','MY','NP','OM','PH','PK','PS','QA','SA','SG',"
            "'SY','TH','TJ','TL','TM','TR','TW','UZ','VN','YE'));"
        )

        session.execute(
            "update country set cnty_continent = 5 where (cnty_cod in('AS','AU','CK','FJ','FM','GU','KI',"
            "'MH','MP','NC','NF','NR','NU','NZ','PF','PG','PN','PW','SB','TK','TO','TV','UM','VU','WF',"
            "'WS'));"
        )

        session.execute(
            "update country set cnty_continent = 6 where (cnty_cod in('AO','BF','BI','BJ','BW','CD','CF',"
            "'CG','CI','CM','CV','DJ','DZ','EG','EH','ER','ET','GA','GH','GM','GN','GQ','GW','KE','KM',"
            "'LR','LS','LY','MA','MG','ML','MR','MU','MW','MZ','NA','NE','NG','RE','RW','SC','SD','SH',"
            "'SL','SN','SO','SS','ST','SZ','TD','TG','TN','TZ','UG','YT','ZA','ZM','ZW'));"
        )

        session.commit()
    except Exception as e:
        print(str(e))
        exit(1)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_country_cnty_continent_continent"), "country", type_="foreignkey"
    )
    op.drop_column("country", "cnty_continent")

    op.add_column(
        "project", sa.Column("project_continent", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_project_project_continent_continent"),
        "project",
        "continent",
        ["project_continent"],
        ["continent_id"],
    )
    # ### end Alembic commands ###
