"""climmobShare - PrjEnumerator - Remove user_name and project_cod

Revision ID: 49199d144454
Revises: 517bff885e43
Create Date: 2021-08-18 10:02:26.945161

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "49199d144454"
down_revision = "517bff885e43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prjenumerator", "user_name")
    op.drop_column("prjenumerator", "project_cod")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prjenumerator",
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "prjenumerator",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
