"""Create table ProjectSummary

Revision ID: 494965d997ef
Revises: 81c52d4df9be
Create Date: 2025-07-01 21:22:59.099348

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "494965d997ef"
down_revision = "81c52d4df9be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_summary",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("psm_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_project_summary_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_project_summary")),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
        mysql_collate="utf8mb4_unicode_ci",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_summary")
    # ### end Alembic commands ###
