"""climmobShare - RegistryJsonLog - Remove user_name and project_cod

Revision ID: 4ca473a2aa38
Revises: d9b9deda13f7
Create Date: 2021-08-26 12:37:38.560049

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ca473a2aa38"
down_revision = "d9b9deda13f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registry_jsonlog", "project_cod")
    op.drop_column("registry_jsonlog", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registry_jsonlog",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "registry_jsonlog",
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
