"""climmobShare - RegistryJsonLog - add project_id

Revision ID: 513d1f08ddc4
Revises: 0be6becb8e09
Create Date: 2021-08-03 13:20:52.038900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from climmob.models.climmobv4 import RegistryJsonLog, Project

# revision identifiers, used by Alembic.
revision = "513d1f08ddc4"
down_revision = "0be6becb8e09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registry_jsonlog",
        sa.Column("project_id", sa.Unicode(length=64), nullable=True),
    )

    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project")
        for project in projects:
            session.execute(
                "UPDATE registry_jsonlog SET project_id = '"
                + project.project_id
                + "' WHERE (user_name = '"
                + project.user_name
                + "') and (project_cod = '"
                + project.project_cod
                + "');"
            )
    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registry_jsonlog", "project_id")
    # ### end Alembic commands ###
