"""climmobShare - Project - Remove user_name

Revision ID: 517bff885e43
Revises: c65271d94458
Create Date: 2021-08-11 10:00:03.279575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "517bff885e43"
down_revision = "c65271d94458"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("user_name", mysql.VARCHAR(length=120), nullable=True)
    )
    # ### end Alembic commands ###
