"""Add field collaboration_accepted to user_project

Revision ID: 53fa2d2caa8a
Revises: 96a20bc8d5fe
Create Date: 2023-03-15 14:12:03.959783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "53fa2d2caa8a"
down_revision = "96a20bc8d5fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_project",
        sa.Column(
            "collaboration_accepted",
            sa.Integer(),
            server_default=sa.text("'1'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_project", "collaboration_accepted")
    # ### end Alembic commands ###
