"""Apply changes in sectors

Revision ID: 55702fd698f4
Revises: 1ac73d917cfd
Create Date: 2023-03-21 15:28:30.255830

"""
from alembic import op
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "55702fd698f4"
down_revision = "1ac73d917cfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    conn = op.get_bind()
    conn.execute(
        "UPDATE sector SET sector_name = 'Alliance Bioversity-CIAT', section_order = '0', section_available = '0' WHERE (sector_cod = '1');"
    )
    conn.execute(
        "UPDATE sector SET sector_name = 'CGIAR', section_order = '1', section_available = '1' WHERE (sector_cod = '2');"
    )
    conn.execute(
        "UPDATE sector SET section_order = '9', section_available = '1' WHERE (sector_cod = '3');"
    )
    conn.execute(
        "UPDATE sector SET sector_name = 'Private sector', section_order = '6', section_available = '1' WHERE (sector_cod = '4');"
    )
    conn.execute(
        "UPDATE sector SET sector_name = 'Public extension', section_order = '7', section_available = '1' WHERE (sector_cod = '5');"
    )
    conn.execute(
        "INSERT INTO sector (sector_cod, sector_name, section_order, section_available) VALUES ('6', 'International organization', '2', '1');"
    )
    conn.execute(
        "INSERT INTO sector (sector_cod, sector_name, section_order, section_available) VALUES ('7', 'Non-governmental organization', '3', '1');"
    )
    conn.execute(
        "INSERT INTO sector (sector_cod, sector_name, section_order, section_available) VALUES ('8', 'Seed company', '4', '1');"
    )
    conn.execute(
        "INSERT INTO sector (sector_cod, sector_name, section_order, section_available) VALUES ('9', 'Service provision to farmers', '5', '1');"
    )
    conn.execute(
        "INSERT INTO sector (sector_cod, sector_name, section_order, section_available) VALUES ('10', 'Public agricultural research', '8', '1');"
    )
    conn.execute(
        "INSERT INTO sector (sector_cod, sector_name, section_order, section_available) VALUES ('11', 'Other', '10', '1');"
    )
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    conn = op.get_bind()
    conn.execute(
        "UPDATE sector SET sector_name = 'Bioversity International', section_order = NULL, section_available = NULL WHERE (sector_cod = '1');"
    )
    conn.execute(
        "UPDATE sector SET sector_name = 'CGIAR Organization', section_order = NULL, section_available = NULL WHERE (sector_cod = '2');"
    )
    conn.execute(
        "UPDATE sector SET section_order = NULL, section_available = NULL WHERE (sector_cod = '3');"
    )
    conn.execute(
        "UPDATE sector SET sector_name = 'Private organization', section_order = NULL, section_available = NULL WHERE (sector_cod = '4');"
    )
    conn.execute(
        "UPDATE sector SET sector_name = 'Public organization', section_order = NULL, section_available = NULL WHERE (sector_cod = '5');"
    )
    conn.execute("DELETE FROM sector WHERE (sector_cod = '6');")
    conn.execute("DELETE FROM sector WHERE (sector_cod = '7');")
    conn.execute("DELETE FROM sector WHERE (sector_cod = '8');")
    conn.execute("DELETE FROM sector WHERE (sector_cod = '9');")
    conn.execute("DELETE FROM sector WHERE (sector_cod = '10');")
    conn.execute("DELETE FROM sector WHERE (sector_cod = '11');")
    session.commit()
    # ### end Alembic commands ###
