"""Create fields project_template_used, project_checked

Revision ID: 5585a156b4b8
Revises: 86a94ddd5bc7
Create Date: 2025-04-02 10:09:02.750225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5585a156b4b8"
down_revision = "86a94ddd5bc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("project_template_used", sa.Unicode(length=64), nullable=True),
    )
    op.add_column(
        "project",
        sa.Column(
            "project_checked",
            sa.Integer(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_project_project_template_used_project"),
        "project",
        "project",
        ["project_template_used"],
        ["project_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_project_project_template_used_project"), "project", type_="foreignkey"
    )
    op.drop_column("project", "project_checked")
    op.drop_column("project", "project_template_used")
    # ### end Alembic commands ###
