"""climmobShare - storageErrors - Remove user_name and project_cod

Revision ID: 5b0921b59c59
Revises: 2410620cc477
Create Date: 2021-08-26 12:35:13.041685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5b0921b59c59"
down_revision = "2410620cc477"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storageerrors", "project_cod")
    op.drop_column("storageerrors", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "storageerrors",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "storageerrors",
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
