"""climmobShare - StorageErrors - table relationship

Revision ID: 5f9c32d90c53
Revises: 17a49eafce9d
Create Date: 2021-08-10 11:23:54.152522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5f9c32d90c53"
down_revision = "17a49eafce9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "storageerrors",
        "project_id",
        existing_type=mysql.VARCHAR(length=64),
        nullable=False,
    )
    op.create_foreign_key(
        op.f("fk_storageerrors_project_id_project"),
        "storageerrors",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_storageerrors_project_id_project"), "storageerrors", type_="foreignkey"
    )
    op.alter_column(
        "storageerrors",
        "project_id",
        existing_type=mysql.VARCHAR(length=64),
        nullable=True,
    )
    # ### end Alembic commands ###
