"""climmobShare - Prjalia - Remove user_name and project_cod

Revision ID: 5fe2394889c0
Revises: ba8456ee74ca
Create Date: 2021-08-18 16:02:17.936066

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5fe2394889c0"
down_revision = "ba8456ee74ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prjalias", "project_cod")
    op.drop_column("prjalias", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prjalias", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "prjalias", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    # ### end Alembic commands ###
