"""climmobShare - Assdetails - Remove user_name and project_cod

Revision ID: 6203e8d86451
Revises: 7e3abf167c88
Create Date: 2021-08-19 14:18:48.021531

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "6203e8d86451"
down_revision = "7e3abf167c88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assdetail", "section_project")
    op.drop_column("assdetail", "project_cod")
    op.drop_column("assdetail", "section_user")
    op.drop_column("assdetail", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assdetail", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "assdetail", sa.Column("section_user", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "assdetail", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "assdetail",
        sa.Column("section_project", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
