"""climmobShare - PrjTech - table relationship

Revision ID: 62077ae5aca5
Revises: 739197b195fd
Create Date: 2021-08-10 11:31:47.522078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62077ae5aca5"
down_revision = "739197b195fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjtech", type_="primary")
    op.create_primary_key("pk_prjtech", "prjtech", ["project_id", "tech_id"])

    op.create_foreign_key(
        op.f("fk_prjtech_tech_id_technology"),
        "prjtech",
        "technology",
        ["tech_id"],
        ["tech_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_prjtech_project_id_project"),
        "prjtech",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjtech", type_="primary")
    op.create_primary_key(
        "pk_prjtech", "prjtech", ["user_name", "project_cod", "tech_id"]
    )

    op.drop_constraint(
        op.f("fk_prjtech_project_id_project"), "prjtech", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_prjtech_tech_id_technology"), "prjtech", type_="foreignkey"
    )
    # ### end Alembic commands ###
