"""add question min and max

Revision ID: 62b9b7d3661c
Revises: 4902d1329fa9
Create Date: 2025-05-16 11:22:23.270993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import String, Integer
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "62b9b7d3661c"
down_revision = "4902d1329fa9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("question", sa.Column("question_min", sa.Float(), nullable=True))
    op.add_column("question", sa.Column("question_max", sa.Float(), nullable=True))

    phrases = [
        {"phrase_id": "38", "phrase_desc": "Must be at least {minimum}"},
        {"phrase_id": "39", "phrase_desc": "Must be at most {maximum}"},
        {
            "phrase_id": "40",
            "phrase_desc": "Must be between {minimum} and {maximum}, inclusive",
        },
    ]

    general_phrases = table(
        "general_phrases",
        column("phrase_id", Integer),
        column("phrase_desc", String),
    )
    op.bulk_insert(general_phrases, phrases)

    i18nPhrases = [
        {
            "phrase_id": 38,
            "user_name": "bioversity",
            "lang_code": "es",
            "phrase_desc": "Debe ser al menos {minimum}",
        },
        {
            "phrase_id": 38,
            "user_name": "bioversity",
            "lang_code": "fr",
            "phrase_desc": "Doit être au moins {minimum}",
        },
        {
            "phrase_id": 39,
            "user_name": "bioversity",
            "lang_code": "es",
            "phrase_desc": "Debe ser como máximo {maximum}",
        },
        {
            "phrase_id": 39,
            "user_name": "bioversity",
            "lang_code": "fr",
            "phrase_desc": "Doit être au maximum {maximum}",
        },
        {
            "phrase_id": 40,
            "user_name": "bioversity",
            "lang_code": "es",
            "phrase_desc": "Debe estar entre {minimum} y {maximum}, inclusive",
        },
        {
            "phrase_id": 40,
            "user_name": "bioversity",
            "lang_code": "fr",
            "phrase_desc": "Doit être compris entre {minimum} et {maximum}, inclus",
        },
    ]

    i18n_general_phrases = table(
        "i18n_general_phrases",
        column("phrase_id", Integer),
        column("user_name", String),
        column("lang_code", String),
        column("phrase_desc", String),
    )
    op.bulk_insert(i18n_general_phrases, i18nPhrases)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("question", "question_max")
    op.drop_column("question", "question_min")

    conn = op.get_bind()

    # Delete from child table first to avoid FK constraint errors
    conn.execute(
        sa.text(
            """
        DELETE FROM i18n_general_phrases
        WHERE phrase_id IN (38, 39, 40)
    """
        )
    )

    conn.execute(
        sa.text(
            """
        DELETE FROM general_phrases
        WHERE phrase_id IN (38, 39, 40)
    """
        )
    )

    # ### end Alembic commands ###
