"""climmobShare - Prjcombdet - Remove user_name and project_cod

Revision ID: 641494781663
Revises: 2d4ef0855b79
Create Date: 2021-08-26 11:21:56.541925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "641494781663"
down_revision = "2d4ef0855b79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prjcombdet", "project_cod")
    op.drop_column("prjcombdet", "prjcomb_user")
    op.drop_column("prjcombdet", "prjcomb_project")
    op.drop_column("prjcombdet", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prjcombdet", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "prjcombdet",
        sa.Column("prjcomb_project", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "prjcombdet",
        sa.Column("prjcomb_user", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "prjcombdet", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    # ### end Alembic commands ###
