"""add field extra to table assessment

Revision ID: 705ed01f1cd6
Revises: 1b05b458a49d
Create Date: 2021-05-11 10:36:10.878386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705ed01f1cd6'
down_revision = '1b05b458a49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('extra', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'extra')
    # ### end Alembic commands ###
