"""climmobShare - PrjEnumerator - table relationship

Revision ID: 739197b195fd
Revises: 5f9c32d90c53
Create Date: 2021-08-10 11:26:20.349179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "739197b195fd"
down_revision = "5f9c32d90c53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjenumerator", type_="primary")
    op.create_primary_key(
        "pk_prjenumerator", "prjenumerator", ["project_id", "enum_user", "enum_id"]
    )

    op.create_foreign_key(
        op.f("fk_prjenumerator_enum_user_enumerator"),
        "prjenumerator",
        "enumerator",
        ["enum_user", "enum_id"],
        ["user_name", "enum_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_prjenumerator_project_id_project"),
        "prjenumerator",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjenumerator", type_="primary")
    op.create_primary_key(
        "pk_prjenumerator",
        "prjenumerator",
        ["user_name", "project_cod", "enum_user", "enum_id"],
    )

    op.drop_constraint(
        op.f("fk_prjenumerator_project_id_project"), "prjenumerator", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_prjenumerator_enum_user_enumerator"),
        "prjenumerator",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
