"""climmobShare - AssessmentJsonLog - Remove user_name and project_cod

Revision ID: 77d1b670f225
Revises: 4ca473a2aa38
Create Date: 2021-08-26 12:38:45.847005

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "77d1b670f225"
down_revision = "4ca473a2aa38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assesment_jsonlog", "user_name")
    op.drop_column("assesment_jsonlog", "project_cod")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assesment_jsonlog",
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "assesment_jsonlog",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
