"""Create tables ProjectObjectives and I18nProjectObjectives

Revision ID: 7af278cfa339
Revises: 18a87d7851ee
Create Date: 2024-11-18 10:59:34.310977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7af278cfa339"
down_revision = "18a87d7851ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_objective",
        sa.Column("pobjective_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pobjective_name", sa.Unicode(length=120), nullable=False),
        sa.Column("pobjective_lang", sa.Unicode(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["pobjective_lang"],
            ["i18n.lang_code"],
            name=op.f("fk_project_objective_pobjective_lang_i18n"),
        ),
        sa.PrimaryKeyConstraint("pobjective_id", name=op.f("pk_project_objective")),
    )
    op.create_table(
        "i18n_project_objective",
        sa.Column("pobjective_id", sa.Integer(), nullable=False),
        sa.Column("lang_code", sa.Unicode(length=5), nullable=False),
        sa.Column("pobjective_name", sa.Unicode(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["i18n.lang_code"],
            name=op.f("fk_i18n_project_objective_lang_code_i18n"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pobjective_id"],
            ["project_objective.pobjective_id"],
            name=op.f("fk_i18n_project_objective_pobjective_id_project_objective"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "pobjective_id", "lang_code", name=op.f("pk_i18n_project_objective")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("i18n_project_objective")
    op.drop_table("project_objective")
    # ### end Alembic commands ###
