"""climmobShare - Asssection - Remove user_name and project_cod

Revision ID: 7e3abf167c88
Revises: f8c906dd9258
Create Date: 2021-08-19 14:15:14.313303

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7e3abf167c88"
down_revision = "f8c906dd9258"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asssection", "user_name")
    op.drop_column("asssection", "project_cod")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asssection", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "asssection", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    # ### end Alembic commands ###
