"""add field question_name to table i18n_question

Revision ID: 7ff846f965e6
Revises: 5e36aa1453be
Create Date: 2021-06-04 14:56:12.294352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ff846f965e6"
down_revision = "5e36aa1453be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "i18n_question",
        sa.Column("question_name", sa.String(length=120), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("i18n_question", "question_name")
    # ### end Alembic commands ###
