"""Add fields pmf_last_update, pmf_lang to table project_metadata_form

Revision ID: 81c52d4df9be
Revises: 62b9b7d3661c
Create Date: 2025-05-30 10:21:28.244765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "81c52d4df9be"
down_revision = "62b9b7d3661c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "project_metadata_form",
        sa.Column("pmf_lang", sa.Unicode(length=5), nullable=True),
    )
    op.add_column(
        "project_metadata_form",
        sa.Column("pmf_last_update", sa.DateTime(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_project_metadata_form_pmf_lang_i18n"),
        "project_metadata_form",
        "i18n",
        ["pmf_lang"],
        ["lang_code"],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        op.f("fk_project_metadata_form_pmf_lang_i18n"),
        "project_metadata_form",
        type_="foreignkey",
    )
    op.drop_column("project_metadata_form", "pmf_last_update")
    op.drop_column("project_metadata_form", "pmf_lang")

    # ### end Alembic commands ###
