"""Create table Affiliation

Revision ID: 86a94ddd5bc7
Revises: bbde4473074f
Create Date: 2025-01-24 09:24:44.856528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "86a94ddd5bc7"
down_revision = "bbde4473074f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "affiliation",
        sa.Column("affiliation_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("affiliation_name", sa.Unicode(length=120), nullable=False),
        sa.PrimaryKeyConstraint("affiliation_id", name=op.f("pk_affiliation")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("affiliation")
    # ### end Alembic commands ###
