"""climmobShare - I18nAsssection - table relationship

Revision ID: 8f39e41f9fed
Revises: 92acbe96af74
Create Date: 2021-08-10 14:26:18.726251

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f39e41f9fed"
down_revision = "92acbe96af74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "i18n_asssection", type_="primary")
    op.create_primary_key(
        "pk_i18n_asssection",
        "i18n_asssection",
        ["project_id", "ass_cod", "section_id", "lang_code"],
    )

    op.create_foreign_key(
        op.f("fk_i18n_asssection_lang_code_i18n"),
        "i18n_asssection",
        "i18n",
        ["lang_code"],
        ["lang_code"],
    )
    op.create_foreign_key(
        op.f("fk_i18n_asssection_project_id_asssection"),
        "i18n_asssection",
        "asssection",
        ["project_id", "ass_cod", "section_id"],
        ["project_id", "ass_cod", "section_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "i18n_asssection", type_="primary")
    op.create_primary_key(
        "pk_i18n_asssection",
        "i18n_asssection",
        ["user_name", "project_cod", "ass_cod", "section_id", "lang_code"],
    )

    op.drop_constraint(
        op.f("fk_i18n_asssection_project_id_asssection"),
        "i18n_asssection",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_i18n_asssection_lang_code_i18n"), "i18n_asssection", type_="foreignkey"
    )
    # ### end Alembic commands ###
