"""create assessment_jsonlog

Revision ID: 8f782ab34aea
Revises: 1748e2fd0987
Create Date: 2020-02-24 13:08:24.667816

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f782ab34aea"
down_revision = "1748e2fd0987"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assesment_jsonlog",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("project_cod", sa.String(length=80), nullable=False),
        sa.Column("ass_cod", sa.String(length=80), nullable=False),
        sa.Column("log_id", sa.Unicode(length=64), nullable=False),
        sa.Column("log_dtime", sa.DateTime(), nullable=True),
        sa.Column("json_file", sa.UnicodeText(), nullable=True),
        sa.Column("log_file", sa.UnicodeText(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name", "project_cod", "ass_cod"],
            ["assessment.user_name", "assessment.project_cod", "assessment.ass_cod"],
            name=op.f("fk_assesment_jsonlog_user_name_assessment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_name",
            "project_cod",
            "ass_cod",
            "log_id",
            name=op.f("pk_assesment_jsonlog"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assesment_jsonlog")
    # ### end Alembic commands ###
