"""add alias fields to project

Revision ID: 9101fad3201f
Revises: 4292187fbaf1
Create Date: 2020-11-10 18:39:38.969091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9101fad3201f"
down_revision = "4292187fbaf1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("project_lang_code", sa.String(length=5), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_project_project_crop_cod_crop_alias"),
        "project",
        "crop_alias",
        ["project_crop_cod", "project_lang_code", "project_alias_cod"],
        ["crop_cod", "lang_code", "alias_cod"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_project_project_crop_cod_crop_alias"), "project", type_="foreignkey"
    )
    op.drop_column("project", "project_lang_code")
    # ### end Alembic commands ###
