"""Add field project_template to Project

Revision ID: 915e1e3bc787
Revises: a29a65a8c33d
Create Date: 2021-11-24 10:12:37.871068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915e1e3bc787'
down_revision = 'a29a65a8c33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_template', sa.Integer(), server_default=sa.text("'0'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_template')
    # ### end Alembic commands ###
