"""climmobShare - Prjcombdet - table relationship

Revision ID: 92acbe96af74
Revises: 745e1dd66f46
Create Date: 2021-08-10 14:09:43.931083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from climmob.models.climmobv4 import Prjcombdet, Project

# revision identifiers, used by Alembic.
revision = "92acbe96af74"
down_revision = "745e1dd66f46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjcombdet", type_="primary")

    op.add_column(
        "prjcombdet",
        sa.Column("project_id_tech", sa.Unicode(length=64), nullable=False),
    )

    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project")
        for project in projects:
            session.query(Prjcombdet).filter_by(project_id=project.project_id).update(
                {"project_id_tech": project.project_id}
            )
    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()

    op.create_primary_key(
        "pk_prjcombdet",
        "prjcombdet",
        ["project_id", "comb_code", "project_id_tech", "tech_id", "alias_id"],
    )

    op.create_index(
        "fk_prjcombdet_prjalias1_idx",
        "prjcombdet",
        ["project_id", "tech_id", "alias_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_prjcombdet_project_id_tech_prjalias"),
        "prjcombdet",
        "prjalias",
        ["project_id_tech", "tech_id", "alias_id"],
        ["project_id", "tech_id", "alias_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_prjcombdet_project_id_prjcombination"),
        "prjcombdet",
        "prjcombination",
        ["project_id", "comb_code"],
        ["project_id", "comb_code"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjcombdet", type_="primary")
    op.create_primary_key(
        "pk_prjcombdet",
        "prjcombdet",
        [
            "prjcomb_user",
            "prjcomb_project",
            "comb_code",
            "user_name",
            "project_cod",
            "tech_id",
            "alias_id",
        ],
    )

    op.drop_constraint(
        op.f("fk_prjcombdet_project_id_prjcombination"),
        "prjcombdet",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_prjcombdet_project_id_tech_prjalias"), "prjcombdet", type_="foreignkey"
    )
    op.drop_index("fk_prjcombdet_prjalias1_idx", table_name="prjcombdet")
    op.drop_column("prjcombdet", "project_id_tech")
    # ### end Alembic commands ###
