"""climmobShare - Pkgcomb - table relationship

Revision ID: 9318991f04ab
Revises: 2619a91dc4a0
Create Date: 2021-08-10 13:49:04.544245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9318991f04ab"
down_revision = "2619a91dc4a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "pkgcomb", type_="primary")
    op.create_primary_key(
        "pk_pkgcomb",
        "pkgcomb",
        ["project_id", "package_id", "comb_project_id", "comb_code"],
    )

    op.create_index(
        "fk_pkgcomb_prjcombination1_idx",
        "pkgcomb",
        ["comb_project_id", "comb_code"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_pkgcomb_project_id_package"),
        "pkgcomb",
        "package",
        ["project_id", "package_id"],
        ["project_id", "package_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_pkgcomb_comb_project_id_prjcombination"),
        "pkgcomb",
        "prjcombination",
        ["comb_project_id", "comb_code"],
        ["project_id", "comb_code"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "pkgcomb", type_="primary")
    op.create_primary_key(
        "pk_pkgcomb",
        "pkgcomb",
        [
            "user_name",
            "project_code",
            "package_id",
            "comb_user",
            "comb_project",
            "comb_code",
        ],
    )

    op.drop_constraint(
        op.f("fk_pkgcomb_comb_project_id_prjcombination"), "pkgcomb", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_pkgcomb_project_id_package"), "pkgcomb", type_="foreignkey"
    )
    op.drop_index("fk_pkgcomb_prjcombination1_idx", table_name="pkgcomb")
    # ### end Alembic commands ###
