"""Add user_secret and user_one_time_code tables

Revision ID: 93e82898a615
Revises: d30d9bf7cd9e
Create Date: 2024-12-18 15:10:42.243564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "93e82898a615"
down_revision = "d30d9bf7cd9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_one_time_code",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_name", sa.Unicode(length=80), nullable=False),
        sa.Column("code", sa.Unicode(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["user.user_name"],
            name=op.f("fk_user_one_time_code_user_name_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_one_time_code")),
    )
    op.create_table(
        "user_secret",
        sa.Column("user_name", sa.Unicode(length=80), nullable=False),
        sa.Column("secret", sa.Unicode(length=120), nullable=False),
        sa.Column("two_fa_method", sa.Unicode(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["user.user_name"],
            name=op.f("fk_user_secret_user_name_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_name", name=op.f("pk_user_secret")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_secret")
    op.drop_table("user_one_time_code")
    # ### end Alembic commands ###
