"""project_id nullable true in table products

Revision ID: 9a521581ab46
Revises: 3bd8d9e330d6
Create Date: 2023-08-04 10:23:38.436579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9a521581ab46"
down_revision = "3bd8d9e330d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "project_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "project_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
