"""climmobShare - Create table user_project

Revision ID: 9f50f9137014
Revises: 6569c037990a
Create Date: 2021-08-10 09:14:05.631131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from climmob.models.climmobv4 import Project, userProject

# revision identifiers, used by Alembic.
revision = "9f50f9137014"
down_revision = "6569c037990a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_project_project_id"), "project", ["project_id"], unique=False
    )

    op.create_table(
        "user_project",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("access_type", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["user.user_name"],
            name=op.f("fk_user_project_user_name_user"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_user_project_project_id_project"),
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "user_name", name=op.f("pk_user_project")
        ),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )

    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project")
        for project in projects:
            pro = userProject(
                project_id=project.project_id,
                user_name=project.user_name,
                access_type=1,
            )
            session.add(pro)
    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_project_user_name"), table_name="user_project")
    op.drop_table("user_project")
    op.drop_index(op.f("ix_project_project_id"), table_name="project")
    # ### end Alembic commands ###
