"""Add fields project_affiliation, climmob_analytics to Table Project

Revision ID: a2842be200b7
Revises: 309b5898cb78
Create Date: 2024-12-17 14:30:54.162113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a2842be200b7"
down_revision = "309b5898cb78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("project_affiliation", sa.Unicode(length=120), nullable=True),
    )
    op.add_column(
        "project", sa.Column("climmob_analytics", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "climmob_analytics")
    op.drop_column("project", "project_affiliation")
    # ### end Alembic commands ###
