"""Add field quantity_available to Prjcombination

Revision ID: a29a65a8c33d
Revises: dded34b92bed
Create Date: 2021-11-09 09:57:30.369481

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a29a65a8c33d"
down_revision = "dded34b92bed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prjcombination", sa.Column("quantity_available", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prjcombination", "quantity_available")
    # ### end Alembic commands ###
