"""create tables for crops

Revision ID: a65f249977b8
Revises: ac44678ec11e
Create Date: 2020-11-10 11:55:49.413403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a65f249977b8"
down_revision = "ac44678ec11e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_categories",
        sa.Column("category_cod", sa.String(length=12), nullable=False),
        sa.Column("category_name", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("category_cod", name=op.f("pk_crop_categories")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "crops",
        sa.Column("crop_cod", sa.String(length=12), nullable=False),
        sa.Column("crop_scientific_name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("crop_cod", name=op.f("pk_crops")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "categoriesbycrop",
        sa.Column("crop_cod", sa.String(length=12), nullable=False),
        sa.Column("category_cod", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_cod"],
            ["crop_categories.category_cod"],
            name=op.f("fk_categoriesbycrop_category_cod_crop_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["crop_cod"],
            ["crops.crop_cod"],
            name=op.f("fk_categoriesbycrop_crop_cod_crops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "crop_cod", "category_cod", name=op.f("pk_categoriesbycrop")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_categoriesbycrop_category_cod"),
        "categoriesbycrop",
        ["category_cod"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categoriesbycrop_crop_cod"),
        "categoriesbycrop",
        ["crop_cod"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categoriesbycrop_crop_cod"), table_name="categoriesbycrop")
    op.drop_index(
        op.f("ix_categoriesbycrop_category_cod"), table_name="categoriesbycrop"
    )
    op.drop_table("categoriesbycrop")
    op.drop_table("crops")
    op.drop_table("crop_categories")
    # ### end Alembic commands ###
