"""remove question_visible field from question

Revision ID: a71511f93b07
Revises: b3e7d84d69d7
Create Date: 2019-10-04 15:34:20.183986

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a71511f93b07"
down_revision = "b3e7d84d69d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_visible")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question",
        sa.Column(
            "question_visible",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
