"""climmobShare - foreign key i18n_question

Revision ID: a71f0b33ceb9
Revises: 9ca963f65ebd
Create Date: 2021-08-10 14:48:18.884482

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "a71f0b33ceb9"
down_revision = "9ca963f65ebd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_i18n_question_lang_code_i18n"),
        "i18n_question",
        "i18n",
        ["lang_code"],
        ["lang_code"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_i18n_question_lang_code_i18n"), "i18n_question", type_="foreignkey"
    )
    # ### end Alembic commands ###
