"""create table qstsubgroups

Revision ID: aa9f50860714
Revises: b38f89fc9856
Create Date: 2020-06-10 10:07:09.675741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa9f50860714'
down_revision = 'b38f89fc9856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qstsubgroups',
    sa.Column('group_username', sa.String(length=80), nullable=False),
    sa.Column('group_id', sa.String(length=80), nullable=False),
    sa.Column('parent_username', sa.String(length=80), nullable=True),
    sa.Column('parent_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['group_username', 'group_id'], ['qstgroups.user_name', 'qstgroups.qstgroups_id'], name=op.f('fk_qstsubgroups_group_username_qstgroups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_username', 'parent_id'], ['qstgroups.user_name', 'qstgroups.qstgroups_id'], name=op.f('fk_qstsubgroups_parent_username_qstgroups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_username', 'group_id', 'parent_username', 'parent_id', name=op.f('pk_qstsubgroups')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qstsubgroups')
    # ### end Alembic commands ###
