"""add field project_registration_and_analysis to project table

Revision ID: ac44678ec11e
Revises: c9bede1ed148
Create Date: 2020-07-16 09:32:31.351875

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ac44678ec11e"
down_revision = "c9bede1ed148"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "project_registration_and_analysis",
            sa.Integer(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_registration_and_analysis")
    # ### end Alembic commands ###
