"""Change metadata_odk to MEDIUMBLOB

Revision ID: ac96c89a6cf7
Revises: f97578512d0c
Create Date: 2025-12-05 15:42:11.958198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ac96c89a6cf7"
down_revision = "f97578512d0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "metadata_form",
        "metadata_odk",
        existing_type=sa.BLOB(),
        type_=mysql.MEDIUMBLOB(),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "metadata_form",
        "metadata_odk",
        existing_type=mysql.MEDIUMBLOB(),
        type_=sa.BLOB(),
    )

    # ### end Alembic commands ###
