"""add groups fields to question

Revision ID: b3e7d84d69d7
Revises: cdf72c1f09d0
Create Date: 2019-10-02 16:26:29.520973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3e7d84d69d7"
down_revision = "cdf72c1f09d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question", sa.Column("qstgroups_id", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "question", sa.Column("qstgroups_user", sa.String(length=80), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_question_qstgroups_user_qstgroups"),
        "question",
        "qstgroups",
        ["qstgroups_user", "qstgroups_id"],
        ["user_name", "qstgroups_id"],
        ondelete=u"CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_question_qstgroups_user_qstgroups"), "question", type_="foreignkey"
    )
    op.drop_column("question", "qstgroups_user")
    op.drop_column("question", "qstgroups_id")
    # ### end Alembic commands ###
