"""climmobShare - I18nRegsection - Remove user_name and project_cod

Revision ID: ba8456ee74ca
Revises: 48ae99a5674b
Create Date: 2021-08-18 14:59:33.831262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ba8456ee74ca"
down_revision = "48ae99a5674b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("i18n_regsection", "project_cod")
    op.drop_column("i18n_regsection", "user_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "i18n_regsection",
        sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False),
    )
    op.add_column(
        "i18n_regsection",
        sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False),
    )
    # ### end Alembic commands ###
