"""Add fields project_curated_cropname, project_continent to Project table

Revision ID: bbde4473074f
Revises: a2842be200b7
Create Date: 2025-01-09 10:56:52.978464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import String, Integer
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "bbde4473074f"
down_revision = "a2842be200b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "continent",
        sa.Column("continent_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("continent_name", sa.Unicode(length=120), nullable=False),
        sa.PrimaryKeyConstraint("continent_id", name=op.f("pk_continent")),
    )

    op.add_column(
        "project",
        sa.Column("project_curated_cropname", sa.Unicode(length=120), nullable=True),
    )
    op.add_column(
        "project", sa.Column("project_continent", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_project_project_continent_continent"),
        "project",
        "continent",
        ["project_continent"],
        ["continent_id"],
    )

    continents = [
        {"continent_id": 1, "continent_name": "America"},
        {"continent_id": 2, "continent_name": "Antarctica"},
        {"continent_id": 3, "continent_name": "Europe"},
        {"continent_id": 4, "continent_name": "Asia"},
        {"continent_id": 5, "continent_name": "Oceania"},
        {"continent_id": 6, "continent_name": "Africa"},
    ]
    continents_table = table(
        "continent",
        column("continent_id", Integer),
        column("continent_name", String),
    )
    op.bulk_insert(continents_table, continents)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_project_project_continent_continent"), "project", type_="foreignkey"
    )
    op.drop_column("project", "project_continent")
    op.drop_column("project", "project_curated_cropname")
    op.drop_table("continent")
    # ### end Alembic commands ###
