"""Regenerating the project status

Revision ID: c61ba397e432
Revises: 2bca2728583a
Create Date: 2025-04-23 17:07:45.834648

"""
from alembic import op
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "c61ba397e432"
down_revision = "2bca2728583a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project WHERE project_status != 3")
        for project in projects:

            if project.project_regstatus == 0:
                value = 1
            else:
                value = 2

            session.execute(
                "UPDATE project SET project_status = '{}' WHERE (`project_id` = '{}');".format(
                    value, project.project_id
                )
            )

    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
