"""add field question_name to question

Revision ID: c9bede1ed148
Revises: aa9f50860714
Create Date: 2020-06-22 09:49:19.796220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c9bede1ed148"
down_revision = "aa9f50860714"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question", sa.Column("question_name", sa.String(length=120), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_name")
    # ### end Alembic commands ###
