"""create table qstgroups

Revision ID: cdf72c1f09d0
Revises: 1d27a4cea25d
Create Date: 2019-10-02 16:19:28.556415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdf72c1f09d0"
down_revision = "1d27a4cea25d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qstgroups",
        sa.Column("user_name", sa.String(length=80), nullable=False),
        sa.Column("qstgroups_id", sa.String(length=80), nullable=False),
        sa.Column("qstgroups_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["user.user_name"],
            name=op.f("fk_qstgroups_user_name_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_name", "qstgroups_id", name=op.f("pk_qstgroups")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("qstgroups")
    # ### end Alembic commands ###
