"""Add field lang_in_climmob to table I18n

Revision ID: d30d9bf7cd9e
Revises: 1913ec52a5af
Create Date: 2024-11-26 11:02:54.298209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d30d9bf7cd9e"
down_revision = "1913ec52a5af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "i18n",
        sa.Column(
            "lang_in_climmob",
            sa.Integer(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("i18n", "lang_in_climmob")
    # ### end Alembic commands ###
