"""climmobShare - Project - table relationship

Revision ID: d33ff297d37a
Revises: 9f50f9137014
Create Date: 2021-08-10 09:34:31.553192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d33ff297d37a"
down_revision = "9f50f9137014"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "project", type_="primary")
    op.create_primary_key("pk_project", "project", ["project_id"])

    """These lines were changed to user_project because there was the problem of the wrongly related table"""
    # op.create_index(
    #    op.f("ix_project_project_id"), "project", ["project_id"], unique=False
    # )
    op.create_foreign_key(
        op.f("fk_project_project_cnty_country"),
        "project",
        "country",
        ["project_cnty"],
        ["cnty_cod"],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "project", type_="primary")
    op.create_primary_key("pk_project", "project", ["user_name", "project_cod"])

    op.drop_constraint(
        op.f("fk_project_project_cnty_country"), "project", type_="foreignkey"
    )
    # op.drop_index(op.f("ix_project_project_id"), table_name="project")
    # ### end Alembic commands ###
