"""Upgrade all dbs to utf8mb4

Revision ID: d44658412201
Revises: 915e1e3bc787
Create Date: 2022-03-05 19:03:36.183372

"""
from alembic import op
from sqlalchemy.orm.session import Session

from climmob.models.climmobv4 import Project, userProject

# revision identifiers, used by Alembic.
revision = 'd44658412201'
down_revision = '915e1e3bc787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    projects = (
        session.query(userProject.user_name, Project.project_cod)
            .filter(userProject.access_type == 1)
            .filter(userProject.project_id == Project.project_id)
            .filter(Project.project_regstatus > 0)
            .all()
    )
    conn = op.get_bind()
    for form in projects:

        queryForDatabase = (
                "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '"
                + form.user_name
                + "_"
                + form.project_cod
                + "'"
        )
        db = conn.execute(queryForDatabase).fetchone()
        if db:
            sql = "ALTER DATABASE {} CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci".format(
                form.user_name + "_" + form.project_cod
            )
            conn.execute(sql)
            sql = (
                "SELECT table_name FROM INFORMATION_SCHEMA.TABLES "
                "WHERE TABLE_TYPE = 'BASE TABLE' and TABLE_SCHEMA = '{}'".format(
                    form.user_name + "_" + form.project_cod
                )
            )
            res = conn.execute(sql)
            conn.execute("SET foreign_key_checks = 0")
            for a_record in res:
                sql = (
                    "ALTER TABLE {}.{} CONVERT TO CHARACTER "
                    "SET utf8mb4 COLLATE utf8mb4_unicode_ci".format(
                        form.user_name + "_" + form.project_cod, a_record[0]
                    )
                )
                conn.execute(sql)
            conn.execute("SET foreign_key_checks = 1")

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
