"""climmobShare - Prjcnty - Remove user_name and project_cod

Revision ID: d9b9deda13f7
Revises: 5b0921b59c59
Create Date: 2021-08-26 12:36:05.237421

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d9b9deda13f7"
down_revision = "5b0921b59c59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prjcnty", "user_name")
    op.drop_column("prjcnty", "project_cod")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prjcnty", sa.Column("project_cod", mysql.VARCHAR(length=80), nullable=False)
    )
    op.add_column(
        "prjcnty", sa.Column("user_name", mysql.VARCHAR(length=80), nullable=False)
    )
    # ### end Alembic commands ###
