"""Adding fields for variety labels (A-B-C)

Revision ID: dded34b92bed
Revises: 2262a820eb66
Create Date: 2021-11-01 15:21:50.683783

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dded34b92bed"
down_revision = "2262a820eb66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "project_label_a",
            sa.Unicode(length=120),
            server_default=sa.text("'Option A'"),
            nullable=False,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "project_label_b",
            sa.Unicode(length=120),
            server_default=sa.text("'Option B'"),
            nullable=False,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "project_label_c",
            sa.Unicode(length=120),
            server_default=sa.text("'Option C'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_label_c")
    op.drop_column("project", "project_label_b")
    op.drop_column("project", "project_label_a")
    # ### end Alembic commands ###
