"""Add field for password reset

Revision ID: de0a6c5ed7b9
Revises: 48af04ae8c55
Create Date: 2023-01-16 12:47:02.471591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "de0a6c5ed7b9"
down_revision = "48af04ae8c55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("user_password_reset_key", sa.Unicode(length=64), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("user_password_reset_token", sa.Unicode(length=64), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("user_password_reset_expires_on", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_password_reset_expires_on")
    op.drop_column("user", "user_password_reset_token")
    op.drop_column("user", "user_password_reset_key")
    # ### end Alembic commands ###
