"""change color to private for sections

Revision ID: e24c6ba5946d
Revises: 771d039833d4
Create Date: 2020-03-19 14:27:55.346790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e24c6ba5946d"
down_revision = "771d039833d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asssection", sa.Column("section_private", sa.Integer(), nullable=True)
    )
    op.drop_column("asssection", "section_color")
    op.add_column(
        "regsection", sa.Column("section_private", sa.Integer(), nullable=True)
    )
    op.drop_column("regsection", "section_color")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regsection",
        sa.Column("section_color", mysql.VARCHAR(length=20), nullable=True),
    )
    op.drop_column("regsection", "section_private")
    op.add_column(
        "asssection",
        sa.Column("section_color", mysql.VARCHAR(length=20), nullable=True),
    )
    op.drop_column("asssection", "section_private")
    # ### end Alembic commands ###
