"""create q-type-anonymity table

Revision ID: e3f8c1e34723
Revises: 1696720fb3c9
Create Date: 2026-05-27 09:21:05.757018

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e3f8c1e34723"
down_revision = "1696720fb3c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_type_anonymity",
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("anonymity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anonymity_id"],
            ["question_anonymity.id"],
            name=op.f("fk_question_type_anonymity_anonymity_id_question_anonymity"),
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["question_type.id"],
            name=op.f("fk_question_type_anonymity_type_id_question_type"),
        ),
        sa.PrimaryKeyConstraint(
            "type_id", "anonymity_id", name=op.f("pk_question_type_anonymity")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_type_anonymity")
    # ### end Alembic commands ###
