"""climmobShare - Prjlang - add project_id

Revision ID: e8be0af780e1
Revises: 48888bc4d0b6
Create Date: 2021-08-03 16:12:38.972394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.orm.session import Session
from climmob.models.climmobv4 import Prjlang, Project

# revision identifiers, used by Alembic.
revision = "e8be0af780e1"
down_revision = "48888bc4d0b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prjlang", sa.Column("project_id", sa.Unicode(length=64), nullable=True)
    )

    session = Session(bind=op.get_bind())
    try:
        projects = session.execute("Select * from project")
        for project in projects:
            session.execute(
                "UPDATE prjlang SET project_id = '"
                + project.project_id
                + "' WHERE (user_name = '"
                + project.user_name
                + "') and (project_cod = '"
                + project.project_cod
                + "');"
            )
    except Exception as e:
        print(str(e))
        exit(1)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prjlang", "project_id")
    # ### end Alembic commands ###
