"""create table chat

Revision ID: f079cff96943
Revises: e24c6ba5946d
Create Date: 2020-03-20 07:29:12.855350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f079cff96943'
down_revision = 'e24c6ba5946d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('chat_message', sa.String(length=500), nullable=True),
    sa.Column('chat_send', sa.Integer(), nullable=True),
    sa.Column('chat_read', sa.Integer(), nullable=True),
    sa.Column('chat_tofrom', sa.Integer(), nullable=True),
    sa.Column('chat_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], name=op.f('fk_chat_user_name_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_name', 'chat_id', name=op.f('pk_chat')),
    mysql_charset="utf8",
    mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###
