"""create anonymization status table

Revision ID: f173e1661605
Revises: 2e83eeec0f3a
Create Date: 2026-05-27 09:54:33.465060

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f173e1661605"
down_revision = "2e83eeec0f3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymization_status",
        sa.Column("anonymization_status_id", sa.Integer(), nullable=False),
        sa.Column("anonymization_status_name", sa.Unicode(length=32), nullable=False),
        sa.PrimaryKeyConstraint(
            "anonymization_status_id", name=op.f("pk_anonymization_status")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anonymization_status")
    # ### end Alembic commands ###
