"""Create table ProjectLocaUnitObjective

Revision ID: f59051fecf09
Revises: 211488d0c5d9
Create Date: 2024-12-06 14:30:35.790338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f59051fecf09"
down_revision = "211488d0c5d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_location_unit_objective",
        sa.Column("plocunitobj_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("pluoaobj_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pluoaobj_id"],
            ["location_unit_of_analysis_objectives.pluoaobj_id"],
            name=op.f(
                "fk_project_location_unit_objective_pluoaobj_id_location_unit_of_analysis_objectives"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_project_location_unit_objective_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "plocunitobj_id", name=op.f("pk_project_location_unit_objective")
        ),
        sa.UniqueConstraint(
            "project_id", "pluoaobj_id", name="uq_project_id_pluoaobj_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_location_unit_objective")
    # ### end Alembic commands ###
