"""climmobShare - Registry - Remove section_user and section_project

Revision ID: f8c906dd9258
Revises: 10cd82efb58d
Create Date: 2021-08-19 14:04:16.017518

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f8c906dd9258"
down_revision = "10cd82efb58d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registry", "section_project")
    op.drop_column("registry", "section_user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registry", sa.Column("section_user", mysql.VARCHAR(length=80), nullable=True)
    )
    op.add_column(
        "registry",
        sa.Column("section_project", mysql.VARCHAR(length=80), nullable=True),
    )
    # ### end Alembic commands ###
