"""add fields to project summary table

Revision ID: f97578512d0c
Revises: 494965d997ef
Create Date: 2025-07-30 09:11:50.555016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f97578512d0c'
down_revision = '494965d997ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('project_summary', sa.Column('admin_user_name', sa.Unicode(length=80), nullable=True))
    op.add_column('project_summary', sa.Column('admin_update_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(op.f('fk_project_summary_admin_user_name_user'), 'project_summary', 'user', ['admin_user_name'], ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('fk_project_summary_admin_user_name_user'), 'project_summary', type_='foreignkey')
    op.drop_column('project_summary', 'admin_update_date')
    op.drop_column('project_summary', 'admin_user_name')

    # ### end Alembic commands ###
