"""climmobShare - Prjlang - table relationship

Revision ID: fef7f1677035
Revises: 62077ae5aca5
Create Date: 2021-08-10 11:35:07.363349

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "fef7f1677035"
down_revision = "62077ae5aca5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjlang", type_="primary")
    op.create_primary_key("pk_project", "prjlang", ["project_id", "lang_code"])

    op.create_foreign_key(
        op.f("fk_prjlang_lang_code_i18n"),
        "prjlang",
        "i18n",
        ["lang_code"],
        ["lang_code"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_prjlang_project_id_project"),
        "prjlang",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "prjlang", type_="primary")
    op.create_primary_key(
        "pk_project", "prjlang", ["user_name", "project_cod", "lang_code"]
    )

    op.drop_constraint(
        op.f("fk_prjlang_project_id_project"), "prjlang", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_prjlang_lang_code_i18n"), "prjlang", type_="foreignkey")
    # ### end Alembic commands ###
