"""climmobShare - Assessment - table relationship

Revision ID: ff292d2df278
Revises: 8cf1a94a5e87
Create Date: 2021-08-10 10:23:40.320958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff292d2df278"
down_revision = "8cf1a94a5e87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "assessment", type_="primary")
    op.create_primary_key("pk_assessment", "assessment", ["project_id", "ass_cod"])

    op.create_foreign_key(
        op.f("fk_assessment_project_id_project"),
        "assessment",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "assessment", type_="primary")
    op.create_primary_key(
        "pk_assessment", "assessment", ["user_name", "project_cod", "ass_cod"]
    )

    op.drop_constraint(
        op.f("fk_assessment_project_id_project"), "assessment", type_="foreignkey"
    )
    # ### end Alembic commands ###
