from celery import Celery
import configparser
import io
from pkg_resources import iter_entry_points
from climmob.config import celery_config

CLIMMOB_INI_FILE = '{{CLIMMOB_INI_FILE}}'
TASKS_ENTRY_POINT_GROUP = 'climmob.tasks'
PLUGINS_ENTRY_POINT_GROUP = 'climmob.plugins'

def just_a_warning():
    ''' This file has been generated by configure_celery
        You should not need to edit this file, however if you
        are moving the installation of Climmob to another directory
        then you either need to call again configure_celery or
        edit the CLIMMOB_INI_FILE so it points to the new path
    '''

def get_ini_value(key,default=None):
    try:
        with open(CLIMMOB_INI_FILE) as f:
            config_file = f.read()
        config = configparser.RawConfigParser(allow_no_value=True)
        config.readfp(io.BytesIO(config_file))
        return config.get('app:climmob', key)
    except:
        return default

def getTasks():
    tasks = []
    plugins = get_ini_value(PLUGINS_ENTRY_POINT_GROUP, '').split()
    for plugin in plugins:
        if isinstance(plugin, str):
            iterator = iter_entry_points(
                group=TASKS_ENTRY_POINT_GROUP,
                name=plugin
            )
            entry_point = next(iterator, None)
            if entry_point:
                tasks.append(entry_point.module_name)
    return tasks

celeryApp = Celery(get_ini_value('celery.taskname'), broker=get_ini_value('celery.broker'), backend=get_ini_value('celery.backend'),include=getTasks())
celeryApp.config_from_object(celery_config)


